import { revalidatePath, revalidateTag } from "next/cache";
import { prisma } from "@/lib/prisma";

export type LedgerPaymentStatus = "PENDING" | "OVERDUE" | "PAID" | "REFUNDED";
export type LedgerInvoiceStatus = "ISSUED" | "SENT" | "OVERDUE" | "PAID" | "CANCELED";
export type LedgerActorType = "ADMIN" | "PARENT" | "SYSTEM" | "WEBHOOK";

type PaymentInvoiceRow = {
    id: string;
    [key: string]: unknown;
};

type ParentInvoiceRow = {
    invoiceId: string;
    paymentId: string;
    studentId: string;
    parentId: string | null;
    invoiceNo: string;
    invoiceStatus: string;
    amount: number;
    title: string;
    description: string | null;
    dueDate: Date;
    issuedAt: Date;
    sentAt: Date | null;
    paidAt: Date | null;
    checkoutUrl: string | null;
    paymentStatus: string;
    paidDate: Date | null;
    method: string | null;
    receiptUrl: string | null;
    studentName: string;
    parentName: string | null;
    parentEmail: string;
    parentPhone: string | null;
    transactionId: string | null;
    orderId: string | null;
    transactionStatus: string | null;
    transactionReceiptUrl: string | null;
};

type CheckoutTransactionRow = {
    id: string;
    orderId: string;
    orderName: string;
    amount: number;
};

type PaymentTransactionRow = {
    id: string;
    paymentId: string;
    invoiceId: string;
    studentId: string;
    parentId: string | null;
    orderId: string;
    amount: number;
    status: string;
    invoiceStatus?: string;
    paymentStatus?: string;
};

function asRecord(value: unknown): Record<string, unknown> {
    return value && typeof value === "object" ? value as Record<string, unknown> : {};
}

function readString(value: unknown): string | null {
    return typeof value === "string" && value.length > 0 ? value : null;
}

function readNumber(value: unknown): number | null {
    return typeof value === "number" && Number.isFinite(value) ? value : null;
}

let _paymentInfrastructureEnsured = false;

export function revalidatePaymentCaches() {
    revalidatePath("/admin/finance");
    revalidatePath("/admin/stats");
    revalidatePath("/mypage");
    revalidateTag("admin-finance", { expire: 0 });
    revalidateTag("admin-stats", { expire: 0 });
}

export async function ensurePaymentInfrastructure() {
    if (_paymentInfrastructureEnsured) return;

    const paymentColumns: [string, string][] = [
        ["type", "TEXT DEFAULT 'MONTHLY'"],
        ["method", "TEXT"],
        ["description", "TEXT"],
        ["month", "INTEGER"],
        ["year", "INTEGER"],
        ["autoGenerated", "BOOLEAN DEFAULT false"],
        ["notifiedAt", "TIMESTAMPTZ"],
        ["invoiceNo", "TEXT"],
        ["issuedAt", "TIMESTAMPTZ"],
        ["payableUntil", "TIMESTAMPTZ"],
        ["paidProvider", "TEXT"],
        ["providerOrderId", "TEXT"],
        ["providerPaymentKey", "TEXT"],
        ["receiptUrl", "TEXT"],
        ["paymentRequestedAt", "TIMESTAMPTZ"],
        ["lastReminderAt", "TIMESTAMPTZ"],
        ["reminderCount", "INTEGER DEFAULT 0"],
    ];

    for (const [column, type] of paymentColumns) {
        await prisma.$executeRawUnsafe(
            `ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "${column}" ${type}`
        );
    }

    await prisma.$executeRawUnsafe(`
        CREATE TABLE IF NOT EXISTS "PaymentInvoice" (
            id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
            "paymentId" TEXT NOT NULL UNIQUE,
            "studentId" TEXT NOT NULL,
            "parentId" TEXT,
            "invoiceNo" TEXT NOT NULL UNIQUE,
            status TEXT NOT NULL DEFAULT 'ISSUED',
            amount INTEGER NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            "dueDate" TIMESTAMPTZ NOT NULL,
            "issuedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            "sentAt" TIMESTAMPTZ,
            "paidAt" TIMESTAMPTZ,
            "canceledAt" TIMESTAMPTZ,
            "lastReminderAt" TIMESTAMPTZ,
            "reminderCount" INTEGER NOT NULL DEFAULT 0,
            "checkoutUrl" TEXT,
            "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);

    await prisma.$executeRawUnsafe(`
        CREATE TABLE IF NOT EXISTS "PaymentTransaction" (
            id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
            "paymentId" TEXT NOT NULL,
            "invoiceId" TEXT NOT NULL,
            "studentId" TEXT NOT NULL,
            "parentId" TEXT,
            provider TEXT NOT NULL DEFAULT 'TOSS',
            "orderId" TEXT NOT NULL UNIQUE,
            "paymentKey" TEXT UNIQUE,
            "orderName" TEXT NOT NULL,
            amount INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'READY',
            method TEXT,
            "receiptUrl" TEXT,
            "failureCode" TEXT,
            "failureMessage" TEXT,
            "requestedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            "approvedAt" TIMESTAMPTZ,
            "rawResponse" JSONB,
            "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);

    await prisma.$executeRawUnsafe(`
        CREATE TABLE IF NOT EXISTS "PaymentWebhookEvent" (
            id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
            provider TEXT NOT NULL DEFAULT 'TOSS',
            "eventId" TEXT,
            "eventType" TEXT,
            "paymentKey" TEXT,
            "orderId" TEXT,
            processed BOOLEAN NOT NULL DEFAULT false,
            "receivedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            "processedAt" TIMESTAMPTZ,
            payload JSONB NOT NULL,
            error TEXT
        )
    `);

    await prisma.$executeRawUnsafe(`
        CREATE TABLE IF NOT EXISTS "PaymentAuditLog" (
            id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
            "paymentId" TEXT,
            "invoiceId" TEXT,
            "transactionId" TEXT,
            "actorType" TEXT NOT NULL,
            "actorId" TEXT,
            action TEXT NOT NULL,
            message TEXT,
            metadata JSONB,
            "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `);

    const indexes = [
        `CREATE INDEX IF NOT EXISTS "Payment_year_month_idx" ON "Payment" (year, month)`,
        `CREATE INDEX IF NOT EXISTS "Payment_status_idx" ON "Payment" (status)`,
        `CREATE INDEX IF NOT EXISTS "Payment_status_dueDate_idx" ON "Payment" (status, "dueDate")`,
        `CREATE INDEX IF NOT EXISTS "Payment_providerOrderId_idx" ON "Payment" ("providerOrderId")`,
        `CREATE INDEX IF NOT EXISTS "Payment_providerPaymentKey_idx" ON "Payment" ("providerPaymentKey")`,
        `CREATE INDEX IF NOT EXISTS "PaymentInvoice_parent_status_idx" ON "PaymentInvoice" ("parentId", status)`,
        `CREATE INDEX IF NOT EXISTS "PaymentInvoice_student_due_idx" ON "PaymentInvoice" ("studentId", "dueDate")`,
        `CREATE INDEX IF NOT EXISTS "PaymentTransaction_invoice_status_idx" ON "PaymentTransaction" ("invoiceId", status)`,
        `CREATE INDEX IF NOT EXISTS "PaymentTransaction_payment_status_idx" ON "PaymentTransaction" ("paymentId", status)`,
        `CREATE INDEX IF NOT EXISTS "PaymentWebhookEvent_order_idx" ON "PaymentWebhookEvent" ("orderId")`,
        `CREATE INDEX IF NOT EXISTS "PaymentWebhookEvent_paymentKey_idx" ON "PaymentWebhookEvent" ("paymentKey")`,
        `CREATE INDEX IF NOT EXISTS "PaymentAuditLog_payment_idx" ON "PaymentAuditLog" ("paymentId", "createdAt" DESC)`,
    ];

    for (const sql of indexes) {
        await prisma.$executeRawUnsafe(sql);
    }

    _paymentInfrastructureEnsured = true;
}

export async function recordPaymentAudit(input: {
    paymentId?: string | null;
    invoiceId?: string | null;
    transactionId?: string | null;
    actorType: LedgerActorType;
    actorId?: string | null;
    action: string;
    message?: string | null;
    metadata?: unknown;
}) {
    await ensurePaymentInfrastructure();
    await prisma.$executeRawUnsafe(
        `INSERT INTO "PaymentAuditLog" (
            id, "paymentId", "invoiceId", "transactionId", "actorType", "actorId",
            action, message, metadata, "createdAt"
        )
        VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, $7, $8::jsonb, NOW())`,
        input.paymentId ?? null,
        input.invoiceId ?? null,
        input.transactionId ?? null,
        input.actorType,
        input.actorId ?? null,
        input.action,
        input.message ?? null,
        JSON.stringify(input.metadata ?? null),
    );
}

export async function ensureInvoicesForMonth(year: number, month: number) {
    await ensurePaymentInfrastructure();

    const dueStart = `${year}-${String(month).padStart(2, "0")}-01`;
    const nextMonth = month === 12 ? 1 : month + 1;
    const nextYear = month === 12 ? year + 1 : year;
    const dueEnd = `${nextYear}-${String(nextMonth).padStart(2, "0")}-01`;

    await prisma.$executeRawUnsafe(
        `
        INSERT INTO "PaymentInvoice" (
            id, "paymentId", "studentId", "parentId", "invoiceNo", status,
            amount, title, description, "dueDate", "issuedAt", "paidAt",
            "createdAt", "updatedAt"
        )
        SELECT
            gen_random_uuid()::text,
            p.id,
            p."studentId",
            s."parentId",
            CONCAT(
                'STIZ-',
                COALESCE(p.year, EXTRACT(YEAR FROM p."dueDate")::int)::text,
                LPAD(COALESCE(p.month, EXTRACT(MONTH FROM p."dueDate")::int)::text, 2, '0'),
                '-',
                SUBSTRING(REPLACE(p.id, '-', '') FROM 1 FOR 8)
            ),
            CASE
                WHEN p.status = 'PAID' THEN 'PAID'
                WHEN p.status = 'REFUNDED' THEN 'CANCELED'
                WHEN p.status = 'OVERDUE' THEN 'OVERDUE'
                ELSE 'ISSUED'
            END,
            p.amount,
            COALESCE(p.description, p.type, '수강료'),
            p.description,
            p."dueDate",
            COALESCE(p."issuedAt", NOW()),
            p."paidDate",
            NOW(),
            NOW()
        FROM "Payment" p
        JOIN "Student" s ON s.id = p."studentId"
        WHERE (
            (p.year = $1 AND p.month = $2)
            OR (p."dueDate" >= $3::timestamp AND p."dueDate" < $4::timestamp)
        )
        ON CONFLICT ("paymentId") DO UPDATE SET
            "studentId" = EXCLUDED."studentId",
            "parentId" = EXCLUDED."parentId",
            amount = EXCLUDED.amount,
            title = EXCLUDED.title,
            description = EXCLUDED.description,
            "dueDate" = EXCLUDED."dueDate",
            status = CASE
                WHEN "PaymentInvoice".status = 'PAID' THEN 'PAID'
                ELSE EXCLUDED.status
            END,
            "paidAt" = COALESCE("PaymentInvoice"."paidAt", EXCLUDED."paidAt"),
            "updatedAt" = NOW()
        `,
        year,
        month,
        dueStart,
        dueEnd,
    );

    await prisma.$executeRawUnsafe(
        `
        UPDATE "Payment" p
        SET
            "invoiceNo" = i."invoiceNo",
            "issuedAt" = COALESCE(p."issuedAt", i."issuedAt"),
            "payableUntil" = COALESCE(p."payableUntil", i."dueDate"),
            "updatedAt" = NOW()
        FROM "PaymentInvoice" i
        WHERE i."paymentId" = p.id
          AND (
            (p.year = $1 AND p.month = $2)
            OR (p."dueDate" >= $3::timestamp AND p."dueDate" < $4::timestamp)
          )
        `,
        year,
        month,
        dueStart,
        dueEnd,
    );

    const rows = await prisma.$queryRawUnsafe<{ count: number }[]>(
        `
        SELECT COUNT(*)::int AS count
        FROM "PaymentInvoice" i
        JOIN "Payment" p ON p.id = i."paymentId"
        WHERE (
            (p.year = $1 AND p.month = $2)
            OR (p."dueDate" >= $3::timestamp AND p."dueDate" < $4::timestamp)
        )
        `,
        year,
        month,
        dueStart,
        dueEnd,
    );

    return { invoiceCount: Number(rows[0]?.count ?? 0) };
}

export async function ensureInvoiceForPayment(paymentId: string) {
    await ensurePaymentInfrastructure();

    const rows = await prisma.$queryRawUnsafe<{ year: number | null; month: number | null; dueDate: Date }[]>(
        `SELECT year, month, "dueDate" FROM "Payment" WHERE id = $1 LIMIT 1`,
        paymentId,
    );
    const payment = rows[0];
    if (!payment) return null;

    const dueDate = new Date(payment.dueDate);
    await ensureInvoicesForMonth(payment.year ?? dueDate.getFullYear(), payment.month ?? dueDate.getMonth() + 1);

    const invoiceRows = await prisma.$queryRawUnsafe<PaymentInvoiceRow[]>(
        `SELECT * FROM "PaymentInvoice" WHERE "paymentId" = $1 LIMIT 1`,
        paymentId,
    );

    return invoiceRows[0] ?? null;
}

export async function markOverduePayments() {
    await ensurePaymentInfrastructure();

    const rows = await prisma.$queryRawUnsafe<{ id: string }[]>(
        `SELECT id FROM "Payment" WHERE status = 'PENDING' AND "dueDate"::date < CURRENT_DATE`
    );

    if (rows.length === 0) return { updated: 0 };

    const ids = rows.map((row) => row.id);
    const placeholders = ids.map((_, index) => `$${index + 1}`).join(",");

    await prisma.$executeRawUnsafe(
        `UPDATE "Payment" SET status = 'OVERDUE', "updatedAt" = NOW() WHERE id IN (${placeholders})`,
        ...ids,
    );

    await prisma.$executeRawUnsafe(
        `UPDATE "PaymentInvoice" SET status = 'OVERDUE', "updatedAt" = NOW()
         WHERE "paymentId" IN (${placeholders}) AND status IN ('ISSUED', 'SENT')`,
        ...ids,
    );

    await recordPaymentAudit({
        actorType: "SYSTEM",
        action: "PAYMENT_MARK_OVERDUE",
        message: `${ids.length} overdue payments marked`,
        metadata: { paymentIds: ids },
    });

    revalidatePaymentCaches();
    return { updated: ids.length };
}

export async function markPaymentPaid(input: {
    paymentId: string;
    invoiceId?: string | null;
    transactionId?: string | null;
    actorType: LedgerActorType;
    actorId?: string | null;
    method?: string | null;
    provider?: string | null;
    orderId?: string | null;
    paymentKey?: string | null;
    receiptUrl?: string | null;
    rawResponse?: unknown;
}) {
    await ensurePaymentInfrastructure();

    const invoice = input.invoiceId
        ? { id: input.invoiceId }
        : await ensureInvoiceForPayment(input.paymentId);

    await prisma.$executeRawUnsafe(
        `UPDATE "Payment"
         SET status = 'PAID',
             "paidDate" = COALESCE("paidDate", NOW()),
             method = COALESCE($2, method),
             "paidProvider" = COALESCE($3, "paidProvider"),
             "providerOrderId" = COALESCE($4, "providerOrderId"),
             "providerPaymentKey" = COALESCE($5, "providerPaymentKey"),
             "receiptUrl" = COALESCE($6, "receiptUrl"),
             "updatedAt" = NOW()
         WHERE id = $1`,
        input.paymentId,
        input.method ?? null,
        input.provider ?? null,
        input.orderId ?? null,
        input.paymentKey ?? null,
        input.receiptUrl ?? null,
    );

    if (invoice?.id) {
        await prisma.$executeRawUnsafe(
            `UPDATE "PaymentInvoice"
             SET status = 'PAID', "paidAt" = COALESCE("paidAt", NOW()), "updatedAt" = NOW()
             WHERE id = $1`,
            invoice.id,
        );
    }

    if (input.transactionId) {
        await prisma.$executeRawUnsafe(
            `UPDATE "PaymentTransaction"
             SET status = 'DONE',
                 "paymentKey" = COALESCE($2, "paymentKey"),
                 method = COALESCE($3, method),
                 "receiptUrl" = COALESCE($4, "receiptUrl"),
                 "approvedAt" = COALESCE("approvedAt", NOW()),
                 "rawResponse" = COALESCE($5::jsonb, "rawResponse"),
                 "updatedAt" = NOW()
             WHERE id = $1`,
            input.transactionId,
            input.paymentKey ?? null,
            input.method ?? null,
            input.receiptUrl ?? null,
            input.rawResponse ? JSON.stringify(input.rawResponse) : null,
        );
    }

    await recordPaymentAudit({
        paymentId: input.paymentId,
        invoiceId: invoice?.id ?? null,
        transactionId: input.transactionId ?? null,
        actorType: input.actorType,
        actorId: input.actorId ?? null,
        action: "PAYMENT_MARK_PAID",
        message: "Payment marked as paid",
        metadata: {
            method: input.method,
            provider: input.provider,
            orderId: input.orderId,
            paymentKey: input.paymentKey ? "[saved]" : null,
        },
    });

    revalidatePaymentCaches();
}

export function getPaymentProviderConfig() {
    const clientKey = process.env.NEXT_PUBLIC_TOSS_PAYMENTS_CLIENT_KEY
        || process.env.TOSS_PAYMENTS_CLIENT_KEY
        || "";
    const secretKey = process.env.TOSS_PAYMENTS_SECRET_KEY || "";

    return {
        clientKey,
        secretKey,
        providerReady: Boolean(clientKey && secretKey),
    };
}

export async function getInvoiceForParent(invoiceId: string, parentEmail: string) {
    await ensurePaymentInfrastructure();

    const rows = await prisma.$queryRawUnsafe<ParentInvoiceRow[]>(
        `
        SELECT
            i.id AS "invoiceId",
            i."paymentId",
            i."studentId",
            i."parentId",
            i."invoiceNo",
            i.status AS "invoiceStatus",
            i.amount,
            i.title,
            i.description,
            i."dueDate",
            i."issuedAt",
            i."sentAt",
            i."paidAt",
            i."checkoutUrl",
            p.status AS "paymentStatus",
            p."paidDate",
            p.method,
            p."receiptUrl",
            s.name AS "studentName",
            u.name AS "parentName",
            u.email AS "parentEmail",
            u.phone AS "parentPhone",
            tx.id AS "transactionId",
            tx."orderId",
            tx.status AS "transactionStatus",
            tx."receiptUrl" AS "transactionReceiptUrl"
        FROM "PaymentInvoice" i
        JOIN "Payment" p ON p.id = i."paymentId"
        JOIN "Student" s ON s.id = i."studentId"
        JOIN "User" u ON u.id = i."parentId"
        LEFT JOIN LATERAL (
            SELECT id, "orderId", status, "receiptUrl"
            FROM "PaymentTransaction"
            WHERE "invoiceId" = i.id
            ORDER BY "createdAt" DESC
            LIMIT 1
        ) tx ON true
        WHERE i.id = $1 AND LOWER(u.email) = LOWER($2)
        LIMIT 1
        `,
        invoiceId,
        parentEmail,
    );

    return rows[0] ?? null;
}

export async function createCheckoutSession(input: {
    invoiceId: string;
    parentEmail: string;
    origin: string;
}) {
    await ensurePaymentInfrastructure();

    const invoice = await getInvoiceForParent(input.invoiceId, input.parentEmail);
    if (!invoice) {
        return { ok: false as const, error: "청구서를 찾을 수 없습니다." };
    }

    if (invoice.paymentStatus === "PAID" || invoice.invoiceStatus === "PAID") {
        return { ok: false as const, error: "이미 납부가 완료된 청구서입니다.", alreadyPaid: true };
    }

    const config = getPaymentProviderConfig();
    const recentRows = await prisma.$queryRawUnsafe<CheckoutTransactionRow[]>(
        `SELECT id, "orderId", "orderName", amount
         FROM "PaymentTransaction"
         WHERE "invoiceId" = $1
           AND status IN ('READY', 'IN_PROGRESS')
           AND "requestedAt" > NOW() - INTERVAL '30 minutes'
         ORDER BY "createdAt" DESC
         LIMIT 1`,
        input.invoiceId,
    );

    const orderName = String(invoice.title || "STIZ 수강료").slice(0, 80);
    const existing = recentRows[0];
    const orderId = existing?.orderId ?? `STIZ-${Date.now()}-${String(input.invoiceId).slice(0, 8)}`;

    if (!existing) {
        await prisma.$executeRawUnsafe(
            `INSERT INTO "PaymentTransaction" (
                id, "paymentId", "invoiceId", "studentId", "parentId", provider,
                "orderId", "orderName", amount, status, "requestedAt", "createdAt", "updatedAt"
            )
            VALUES (
                gen_random_uuid()::text, $1, $2, $3, $4, 'TOSS',
                $5, $6, $7, 'READY', NOW(), NOW(), NOW()
            )`,
            invoice.paymentId,
            invoice.invoiceId,
            invoice.studentId,
            invoice.parentId,
            orderId,
            orderName,
            Number(invoice.amount),
        );
    }

    await prisma.$executeRawUnsafe(
        `UPDATE "Payment"
         SET "paymentRequestedAt" = NOW(), "updatedAt" = NOW()
         WHERE id = $1`,
        invoice.paymentId,
    );

    const cleanOrigin = input.origin.replace(/\/$/, "");
    const successUrl = `${cleanOrigin}/payments/success`;
    const failUrl = `${cleanOrigin}/payments/fail`;

    return {
        ok: true as const,
        providerReady: config.providerReady,
        clientKey: config.clientKey,
        customerKey: Buffer.from(String(invoice.parentId || invoice.parentEmail || "stiz-parent"))
            .toString("base64")
            .replace(/\+/g, "-")
            .replace(/\//g, "_")
            .replace(/=+$/g, "")
            .slice(0, 50),
        orderId,
        amount: Number(invoice.amount),
        orderName,
        customerName: invoice.parentName || invoice.studentName || "STIZ 학부모",
        customerEmail: invoice.parentEmail,
        successUrl,
        failUrl,
    };
}

function encodeTossSecret(secretKey: string) {
    return Buffer.from(`${secretKey}:`).toString("base64");
}

export async function confirmTossPayment(input: {
    paymentKey: string;
    orderId: string;
    amount: number;
}) {
    await ensurePaymentInfrastructure();

    const txRows = await prisma.$queryRawUnsafe<PaymentTransactionRow[]>(
        `SELECT tx.*, i.status AS "invoiceStatus", p.status AS "paymentStatus"
         FROM "PaymentTransaction" tx
         JOIN "PaymentInvoice" i ON i.id = tx."invoiceId"
         JOIN "Payment" p ON p.id = tx."paymentId"
         WHERE tx."orderId" = $1
         LIMIT 1`,
        input.orderId,
    );
    const tx = txRows[0];
    if (!tx) return { ok: false as const, error: "결제 주문을 찾을 수 없습니다." };

    if (Number(tx.amount) !== Number(input.amount)) {
        await prisma.$executeRawUnsafe(
            `UPDATE "PaymentTransaction"
             SET status = 'ABORTED', "failureCode" = 'AMOUNT_MISMATCH',
                 "failureMessage" = '결제 금액이 청구 금액과 다릅니다.', "updatedAt" = NOW()
             WHERE id = $1`,
            tx.id,
        );
        return { ok: false as const, error: "결제 금액이 청구 금액과 다릅니다." };
    }

    if (tx.status === "DONE" || tx.paymentStatus === "PAID" || tx.invoiceStatus === "PAID") {
        return { ok: true as const, alreadyConfirmed: true };
    }

    const { secretKey } = getPaymentProviderConfig();
    if (!secretKey) {
        return { ok: false as const, error: "Toss Payments 서버 키가 설정되어 있지 않습니다." };
    }

    const response = await fetch("https://api.tosspayments.com/v1/payments/confirm", {
        method: "POST",
        headers: {
            Authorization: `Basic ${encodeTossSecret(secretKey)}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            paymentKey: input.paymentKey,
            orderId: input.orderId,
            amount: Number(input.amount),
        }),
    });

    const result = await response.json();

    if (!response.ok) {
        await prisma.$executeRawUnsafe(
            `UPDATE "PaymentTransaction"
             SET status = 'ABORTED',
                 "paymentKey" = $2,
                 "failureCode" = $3,
                 "failureMessage" = $4,
                 "rawResponse" = $5::jsonb,
                 "updatedAt" = NOW()
             WHERE id = $1`,
            tx.id,
            input.paymentKey,
            result.code ?? "TOSS_CONFIRM_FAILED",
            result.message ?? "Toss payment confirm failed",
            JSON.stringify(result),
        );
        return { ok: false as const, error: result.message ?? "결제 승인에 실패했습니다." };
    }

    const method = result.method ?? null;
    const receiptUrl = result.receipt?.url ?? result.card?.receiptUrl ?? null;

    await markPaymentPaid({
        paymentId: tx.paymentId,
        invoiceId: tx.invoiceId,
        transactionId: tx.id,
        actorType: "PARENT",
        actorId: tx.parentId ?? null,
        method,
        provider: "TOSS",
        orderId: input.orderId,
        paymentKey: input.paymentKey,
        receiptUrl,
        rawResponse: result,
    });

    return { ok: true as const, payment: result };
}

export async function recordTossWebhook(payload: unknown) {
    await ensurePaymentInfrastructure();

    const payloadRecord = asRecord(payload);
    const data = asRecord(payloadRecord.data ?? payload);
    const eventId = readString(payloadRecord.eventId) ?? readString(payloadRecord.id);
    const eventType = readString(payloadRecord.eventType) ?? readString(payloadRecord.type) ?? readString(data.status);
    const paymentKey = readString(data.paymentKey);
    const orderId = readString(data.orderId);

    const eventRows = await prisma.$queryRawUnsafe<{ id: string }[]>(
        `INSERT INTO "PaymentWebhookEvent" (
            id, provider, "eventId", "eventType", "paymentKey", "orderId",
            payload, "receivedAt"
        )
        VALUES (gen_random_uuid()::text, 'TOSS', $1, $2, $3, $4, $5::jsonb, NOW())
        RETURNING id`,
        eventId,
        eventType,
        paymentKey,
        orderId,
        JSON.stringify(payload),
    );

    const eventRecordId = eventRows[0]?.id ?? null;
    if (!orderId && !paymentKey) {
        return { ok: true as const, processed: false, eventId: eventRecordId };
    }

    const txRows = await prisma.$queryRawUnsafe<PaymentTransactionRow[]>(
        `SELECT * FROM "PaymentTransaction"
         WHERE "orderId" = $1 OR "paymentKey" = $2
         ORDER BY "createdAt" DESC
         LIMIT 1`,
        orderId,
        paymentKey,
    );
    const tx = txRows[0];
    if (!tx) {
        await prisma.$executeRawUnsafe(
            `UPDATE "PaymentWebhookEvent"
             SET error = 'TRANSACTION_NOT_FOUND', "processedAt" = NOW()
             WHERE id = $1`,
            eventRecordId,
        );
        return { ok: true as const, processed: false, eventId: eventRecordId };
    }

    const webhookAmount = readNumber(data.totalAmount) ?? readNumber(data.amount) ?? Number(tx.amount);
    if (data.status === "DONE" && Number(webhookAmount) === Number(tx.amount)) {
        await markPaymentPaid({
            paymentId: tx.paymentId,
            invoiceId: tx.invoiceId,
            transactionId: tx.id,
            actorType: "WEBHOOK",
            method: readString(data.method),
            provider: "TOSS",
            orderId: tx.orderId,
            paymentKey,
            receiptUrl: readString(asRecord(data.receipt).url),
            rawResponse: payload,
        });

        await prisma.$executeRawUnsafe(
            `UPDATE "PaymentWebhookEvent"
             SET processed = true, "processedAt" = NOW()
             WHERE id = $1`,
            eventRecordId,
        );
    }

    return { ok: true as const, processed: true, eventId: eventRecordId };
}
