"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
    createPayment,
    updatePaymentStatus,
    deletePayment,
    generateMonthlyInvoices,
    sendUnpaidReminders,
    bulkUpdatePaymentStatus,
} from "@/app/actions/admin";

type Payment = {
    id: string;
    studentId: string;
    studentName: string;
    amount: number;
    status: string;
    dueDate: Date | string;
    paidDate: Date | string | null;
    type: string;
    description: string | null;
    month: number | null;
    year: number | null;
    autoGenerated: boolean;
    notifiedAt: Date | string | null;
    createdAt: Date | string;
};

type Student = {
    id: string;
    name: string;
};

type Summary = {
    totalCount: number;
    totalAmount: number;
    paidAmount: number;
    unpaidAmount: number;
    paidCount: number;
    unpaidCount: number;
};

// 상태 라벨 + 색상 매핑
const STATUS_LABELS: Record<string, { label: string; color: string }> = {
    PENDING: { label: "미납", color: "bg-yellow-100 text-yellow-700" },
    PAID: { label: "납부완료", color: "bg-green-100 text-green-700" },
    OVERDUE: { label: "연체", color: "bg-red-100 text-red-700" },
    REFUNDED: { label: "환불", color: "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300" },
};

// 청구 유형 라벨
const TYPE_LABELS: Record<string, string> = {
    MONTHLY: "수강료",
    SHUTTLE: "셔틀",
    UNIFORM: "유니폼",
    OTHER: "기타",
};

function toDateStr(d: Date | string | null): string {
    if (!d) return "-";
    const date = typeof d === "string" ? new Date(d) : d;
    return date.toISOString().split("T")[0];
}

function formatAmount(n: number): string {
    return n.toLocaleString("ko-KR") + "원";
}

export default function FinanceClient({
    initialPayments,
    students,
    initialYear,
    initialMonth,
    initialSummary,
}: {
    initialPayments: Payment[];
    students: Student[];
    initialYear: number;
    initialMonth: number;
    initialSummary: Summary;
}) {
    const router = useRouter();
    const [payments, setPayments] = useState(initialPayments);
    const [year, setYear] = useState(initialYear);
    const [month, setMonth] = useState(initialMonth);
    const [showForm, setShowForm] = useState(false);
    const [busy, setBusy] = useState(false);
    const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);
    const [summary, setSummary] = useState(initialSummary);

    // 일괄 체크박스 상태
    const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());

    // 수동 생성 폼 상태
    const [studentId, setStudentId] = useState("");
    const [amount, setAmount] = useState(0);
    const [dueDate, setDueDate] = useState("");
    const [status, setStatus] = useState("PENDING");
    const [paymentType, setPaymentType] = useState("MONTHLY");
    const [description, setDescription] = useState("");

    // 월 이동 시 데이터 재조회
    async function loadMonth(y: number, m: number) {
        setYear(y);
        setMonth(m);
        setSelectedIds(new Set()); // 선택 초기화
        try {
            const res = await fetch(`/api/admin/finance?year=${y}&month=${m}`);
            if (res.ok) {
                const data = await res.json();
                setPayments(data);
                // 요약 재계산 (클라이언트 측)
                const total = data.reduce((s: number, p: any) => s + p.amount, 0);
                const paid = data.filter((p: any) => p.status === "PAID").reduce((s: number, p: any) => s + p.amount, 0);
                const unpaid = data.filter((p: any) => p.status === "PENDING" || p.status === "OVERDUE").reduce((s: number, p: any) => s + p.amount, 0);
                setSummary({
                    totalCount: data.length,
                    totalAmount: total,
                    paidAmount: paid,
                    unpaidAmount: unpaid,
                    paidCount: data.filter((p: any) => p.status === "PAID").length,
                    unpaidCount: data.filter((p: any) => p.status === "PENDING" || p.status === "OVERDUE").length,
                });
            }
        } catch (err) {
            // 조회 실패 시 사용자에게 피드백 제공
            console.error("수납 데이터 조회 실패:", err);
            alert("수납 데이터를 불러오지 못했습니다. 다시 시도해 주세요.");
        }
    }

    function prevMonth() {
        const m = month === 1 ? 12 : month - 1;
        const y = month === 1 ? year - 1 : year;
        loadMonth(y, m);
    }

    function nextMonth() {
        const m = month === 12 ? 1 : month + 1;
        const y = month === 12 ? year + 1 : year;
        loadMonth(y, m);
    }

    // 수납 기록 수동 생성
    async function handleCreate(e: React.FormEvent) {
        e.preventDefault();
        if (!studentId || !amount || !dueDate) return;
        setBusy(true);
        try {
            // type과 description도 함께 전달 (수동 생성 시 유형/설명 저장)
            await createPayment({ studentId, amount, dueDate, status, type: paymentType, description: description || undefined });
            setShowForm(false);
            setStudentId("");
            setAmount(0);
            setDueDate("");
            setStatus("PENDING");
            setPaymentType("MONTHLY");
            setDescription("");
            router.refresh();
            loadMonth(year, month);
        } catch (err: any) {
            alert(err.message || "생성 실패");
        } finally {
            setBusy(false);
        }
    }

    // 개별 상태 변경
    async function handleStatusChange(id: string, newStatus: string) {
        setBusy(true);
        try {
            await updatePaymentStatus(id, newStatus);
            router.refresh();
            loadMonth(year, month);
        } catch (err: any) {
            alert(err.message || "상태 변경 실패");
        } finally {
            setBusy(false);
        }
    }

    // 개별 삭제
    async function handleDelete(id: string) {
        setBusy(true);
        try {
            await deletePayment(id);
            setDeleteConfirm(null);
            router.refresh();
            loadMonth(year, month);
        } catch (err: any) {
            alert(err.message || "삭제 실패");
        } finally {
            setBusy(false);
        }
    }

    // 이달 청구서 자동 생성
    async function handleGenerateInvoices() {
        if (!confirm(`${year}년 ${month}월 청구서를 자동 생성하시겠습니까?\n활성 템플릿 기준으로 모든 수강생에게 청구서가 생성됩니다.`)) return;
        setBusy(true);
        try {
            const result = await generateMonthlyInvoices(year, month);
            alert(result.message);
            router.refresh();
            loadMonth(year, month);
        } catch (err: any) {
            alert(err.message || "청구서 생성 실패");
        } finally {
            setBusy(false);
        }
    }

    // 미납 알림 일괄 발송
    async function handleSendReminders() {
        if (!confirm("미납 건에 대해 학부모 알림을 발송하시겠습니까?")) return;
        setBusy(true);
        try {
            const result = await sendUnpaidReminders();
            alert(result.message);
            router.refresh();
            loadMonth(year, month);
        } catch (err: any) {
            alert(err.message || "알림 발송 실패");
        } finally {
            setBusy(false);
        }
    }

    // 일괄 수납 처리
    async function handleBulkPaid() {
        if (selectedIds.size === 0) { alert("선택된 항목이 없습니다."); return; }
        if (!confirm(`선택한 ${selectedIds.size}건을 납부완료 처리하시겠습니까?`)) return;
        setBusy(true);
        try {
            await bulkUpdatePaymentStatus(Array.from(selectedIds), "PAID");
            setSelectedIds(new Set());
            router.refresh();
            loadMonth(year, month);
        } catch (err: any) {
            alert(err.message || "일괄 처리 실패");
        } finally {
            setBusy(false);
        }
    }

    // 체크박스: 전체 선택/해제
    function toggleSelectAll() {
        if (selectedIds.size === payments.length) {
            setSelectedIds(new Set());
        } else {
            setSelectedIds(new Set(payments.map((p) => p.id)));
        }
    }

    // 체크박스: 개별 토글
    function toggleSelect(id: string) {
        const next = new Set(selectedIds);
        if (next.has(id)) next.delete(id);
        else next.add(id);
        setSelectedIds(next);
    }

    // 수납률 계산
    const payRate = summary.totalAmount > 0
        ? Math.round((summary.paidAmount / summary.totalAmount) * 100)
        : 0;

    return (
        <div className="max-w-5xl mx-auto">
            {/* 헤더 + 액션 버튼 */}
            <div className="flex flex-wrap justify-between items-start gap-3 mb-6">
                <div>
                    <h1 className="text-2xl font-extrabold text-gray-900 dark:text-white">수납/결제 관리</h1>
                    <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">원생별 수납 현황을 관리합니다.</p>
                </div>
                <div className="flex flex-wrap gap-2">
                    {/* 이달 청구서 생성 버튼 */}
                    <button
                        onClick={handleGenerateInvoices}
                        disabled={busy}
                        className="bg-blue-600 text-white px-4 py-2 rounded-lg font-bold hover:bg-blue-700 transition disabled:opacity-50 text-sm"
                    >
                        <span className="material-symbols-outlined text-sm align-middle mr-1">receipt_long</span>
                        이달 청구서 생성
                    </button>
                    {/* 미납 알림 발송 버튼 */}
                    <button
                        onClick={handleSendReminders}
                        disabled={busy}
                        className="bg-yellow-500 text-white px-4 py-2 rounded-lg font-bold hover:bg-yellow-600 transition disabled:opacity-50 text-sm"
                    >
                        <span className="material-symbols-outlined text-sm align-middle mr-1">notifications_active</span>
                        미납 알림 발송
                    </button>
                    {/* 수동 추가 버튼 */}
                    <button
                        onClick={() => setShowForm(!showForm)}
                        className="bg-brand-orange-500 dark:bg-brand-neon-lime dark:text-brand-navy-900 text-white px-4 py-2 rounded-lg font-bold hover:bg-orange-600 transition text-sm"
                    >
                        + 수납 기록 추가
                    </button>
                </div>
            </div>

            {/* 월 네비게이션 */}
            <div className="flex items-center gap-4 mb-6">
                <button onClick={prevMonth} className="p-2 hover:bg-gray-100 dark:bg-gray-800 rounded-lg text-gray-600 dark:text-gray-300 font-bold">&larr;</button>
                <span className="text-lg font-bold text-gray-900 dark:text-white">{year}년 {month}월</span>
                <button onClick={nextMonth} className="p-2 hover:bg-gray-100 dark:bg-gray-800 rounded-lg text-gray-600 dark:text-gray-300 font-bold">&rarr;</button>
            </div>

            {/* 요약 카드 (4개: 총 청구/수납/미납/수납률) */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
                <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-4">
                    <p className="text-xs text-gray-500 dark:text-gray-400 font-medium">총 청구</p>
                    <p className="text-xl font-extrabold text-gray-900 dark:text-white mt-1">{formatAmount(summary.totalAmount)}</p>
                    <p className="text-xs text-gray-400 mt-0.5">{summary.totalCount}건</p>
                </div>
                <div className="bg-white dark:bg-gray-800 border border-green-200 rounded-xl p-4">
                    <p className="text-xs text-green-600 font-medium">납부완료</p>
                    <p className="text-xl font-extrabold text-green-700 mt-1">{formatAmount(summary.paidAmount)}</p>
                    <p className="text-xs text-green-500 mt-0.5">{summary.paidCount}건</p>
                </div>
                <div className="bg-white dark:bg-gray-800 border border-yellow-200 rounded-xl p-4">
                    <p className="text-xs text-yellow-600 font-medium">미납/연체</p>
                    <p className="text-xl font-extrabold text-yellow-700 mt-1">{formatAmount(summary.unpaidAmount)}</p>
                    <p className="text-xs text-yellow-500 mt-0.5">{summary.unpaidCount}건</p>
                </div>
                <div className="bg-white dark:bg-gray-800 border border-blue-200 rounded-xl p-4">
                    <p className="text-xs text-blue-600 font-medium">수납률</p>
                    <p className="text-xl font-extrabold text-blue-700 mt-1">{payRate}%</p>
                    <div className="w-full bg-gray-200 rounded-full h-1.5 mt-2">
                        <div className="bg-blue-500 h-1.5 rounded-full transition-all" style={{ width: `${payRate}%` }} />
                    </div>
                </div>
            </div>

            {/* 일괄 처리 바 — 선택된 항목이 있을 때만 표시 */}
            {selectedIds.size > 0 && (
                <div className="bg-blue-50 border border-blue-200 rounded-xl p-3 mb-4 flex items-center justify-between">
                    <span className="text-sm font-medium text-blue-700">
                        {selectedIds.size}건 선택됨
                    </span>
                    <button
                        onClick={handleBulkPaid}
                        disabled={busy}
                        className="bg-green-600 text-white px-4 py-1.5 rounded-lg text-sm font-bold hover:bg-green-700 transition disabled:opacity-50"
                    >
                        선택 항목 납부 처리
                    </button>
                </div>
            )}

            {/* 수동 생성 폼 */}
            {showForm && (
                <form onSubmit={handleCreate} className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-6 mb-6 shadow-sm space-y-4">
                    <h3 className="font-bold text-lg text-gray-900 dark:text-white">새 수납 기록</h3>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">원생 *</label>
                            <select
                                value={studentId}
                                onChange={(e) => setStudentId(e.target.value)}
                                required
                                className="w-full border border-gray-300 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime bg-white dark:bg-gray-800"
                            >
                                <option value="">선택하세요</option>
                                {students.map((s) => (
                                    <option key={s.id} value={s.id}>{s.name}</option>
                                ))}
                            </select>
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">금액 (원) *</label>
                            <input
                                type="number"
                                value={amount || ""}
                                onChange={(e) => setAmount(parseInt(e.target.value) || 0)}
                                required
                                placeholder="100000"
                                className="w-full border border-gray-300 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">납부 기한 *</label>
                            <input
                                type="date"
                                min="2020-01-01" max="2030-12-31"
                                value={dueDate}
                                onChange={(e) => setDueDate(e.target.value)}
                                required
                                className="w-full border border-gray-300 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">유형</label>
                            <select
                                value={paymentType}
                                onChange={(e) => setPaymentType(e.target.value)}
                                className="w-full border border-gray-300 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime bg-white dark:bg-gray-800"
                            >
                                <option value="MONTHLY">월 수강료</option>
                                <option value="SHUTTLE">셔틀</option>
                                <option value="UNIFORM">유니폼</option>
                                <option value="OTHER">기타</option>
                            </select>
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">상태</label>
                            <select
                                value={status}
                                onChange={(e) => setStatus(e.target.value)}
                                className="w-full border border-gray-300 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime bg-white dark:bg-gray-800"
                            >
                                <option value="PENDING">미납</option>
                                <option value="PAID">납부완료</option>
                                <option value="OVERDUE">연체</option>
                            </select>
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">설명 (선택)</label>
                            <input
                                type="text"
                                value={description}
                                onChange={(e) => setDescription(e.target.value)}
                                placeholder="예: 4월 수강료"
                                className="w-full border border-gray-300 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime"
                            />
                        </div>
                    </div>
                    <div className="flex gap-2 justify-end">
                        <button type="button" onClick={() => setShowForm(false)} className="px-4 py-2 text-sm text-gray-600 dark:text-gray-300">취소</button>
                        <button type="submit" disabled={busy} className="bg-brand-orange-500 dark:bg-brand-neon-lime dark:text-brand-navy-900 text-white px-6 py-2 rounded-lg font-bold hover:bg-orange-600 transition disabled:opacity-50">
                            {busy ? "저장 중..." : "추가"}
                        </button>
                    </div>
                </form>
            )}

            {/* 수납 목록 테이블 */}
            {payments.length === 0 ? (
                <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-12 text-center text-gray-400">
                    {year}년 {month}월 수납 기록이 없습니다.
                </div>
            ) : (
                <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden shadow-sm">
                    <div className="overflow-x-auto">
                        <table className="min-w-full divide-y divide-gray-200">
                            <thead className="bg-gray-50 dark:bg-gray-900">
                                <tr>
                                    {/* 전체 선택 체크박스 */}
                                    <th className="px-3 py-3 text-center">
                                        <input
                                            type="checkbox"
                                            checked={selectedIds.size === payments.length && payments.length > 0}
                                            onChange={toggleSelectAll}
                                            className="rounded border-gray-300"
                                        />
                                    </th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">원생</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">유형</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">금액</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">납부기한</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">납부일</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">상태</th>
                                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">관리</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100">
                                {payments.map((p) => {
                                    const statusInfo = STATUS_LABELS[p.status] || STATUS_LABELS.PENDING;
                                    return (
                                        <tr key={p.id} className={`hover:bg-gray-50 dark:bg-gray-900 transition-colors ${selectedIds.has(p.id) ? "bg-blue-50" : ""}`}>
                                            {/* 개별 체크박스 */}
                                            <td className="px-3 py-3.5 text-center">
                                                <input
                                                    type="checkbox"
                                                    checked={selectedIds.has(p.id)}
                                                    onChange={() => toggleSelect(p.id)}
                                                    className="rounded border-gray-300"
                                                />
                                            </td>
                                            <td className="px-4 py-3.5">
                                                <span className="font-medium text-gray-900 dark:text-white">{p.studentName}</span>
                                                {p.description && (
                                                    <p className="text-xs text-gray-400 mt-0.5">{p.description}</p>
                                                )}
                                                {p.autoGenerated && (
                                                    <span className="text-[10px] bg-blue-50 text-blue-500 px-1.5 py-0.5 rounded ml-1">자동</span>
                                                )}
                                            </td>
                                            <td className="px-4 py-3.5 text-sm text-gray-600 dark:text-gray-300">
                                                {TYPE_LABELS[p.type] || p.type}
                                            </td>
                                            <td className="px-4 py-3.5 text-sm text-gray-700 dark:text-gray-200 font-mono">{formatAmount(p.amount)}</td>
                                            <td className="px-4 py-3.5 text-sm text-gray-600 dark:text-gray-300">{toDateStr(p.dueDate)}</td>
                                            <td className="px-4 py-3.5 text-sm text-gray-600 dark:text-gray-300">{toDateStr(p.paidDate)}</td>
                                            <td className="px-4 py-3.5">
                                                <span className={`text-xs font-bold px-2 py-1 rounded-full ${statusInfo.color}`}>
                                                    {statusInfo.label}
                                                </span>
                                                {p.notifiedAt && (
                                                    <span className="text-[10px] text-gray-400 block mt-0.5">
                                                        알림 {toDateStr(p.notifiedAt)}
                                                    </span>
                                                )}
                                            </td>
                                            <td className="px-4 py-3.5 text-right">
                                                <div className="flex items-center gap-2 justify-end">
                                                    {p.status !== "PAID" && (
                                                        <button
                                                            onClick={() => handleStatusChange(p.id, "PAID")}
                                                            disabled={busy}
                                                            className="text-xs text-green-600 hover:text-green-800 font-medium"
                                                        >
                                                            납부처리
                                                        </button>
                                                    )}
                                                    {p.status === "PENDING" && (
                                                        <button
                                                            onClick={() => handleStatusChange(p.id, "OVERDUE")}
                                                            disabled={busy}
                                                            className="text-xs text-yellow-600 hover:text-yellow-800 font-medium"
                                                        >
                                                            연체처리
                                                        </button>
                                                    )}
                                                    {p.status === "PAID" && (
                                                        <button
                                                            onClick={() => handleStatusChange(p.id, "REFUNDED")}
                                                            disabled={busy}
                                                            className="text-xs text-gray-500 hover:text-gray-700 dark:text-gray-200 font-medium"
                                                        >
                                                            환불
                                                        </button>
                                                    )}
                                                    {deleteConfirm === p.id ? (
                                                        <div className="flex gap-1">
                                                            <button onClick={() => handleDelete(p.id)} disabled={busy}
                                                                className="text-xs bg-red-500 text-white px-2 py-1 rounded font-bold disabled:opacity-50">확인</button>
                                                            <button onClick={() => setDeleteConfirm(null)}
                                                                className="text-xs text-gray-500 dark:text-gray-400 px-2 py-1">취소</button>
                                                        </div>
                                                    ) : (
                                                        <button onClick={() => setDeleteConfirm(p.id)}
                                                            className="text-xs text-red-500 hover:text-red-700 font-medium">삭제</button>
                                                    )}
                                                </div>
                                            </td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
}
