"use client";

import { useCallback, useEffect, useState } from "react";
import {
    createPayment,
    updatePaymentStatus,
    deletePayment,
    previewMonthlyInvoices,
    generateMonthlyInvoices,
    refreshPaymentLedger,
    sendUnpaidReminders,
    bulkUpdatePaymentStatus,
} from "@/app/actions/admin";

type Payment = {
    id: string;
    studentId: string;
    studentName: string;
    amount: number;
    status: string;
    dueDate: Date | string;
    paidDate: Date | string | null;
    type: string;
    description: string | null;
    month: number | null;
    year: number | null;
    autoGenerated: boolean;
    notifiedAt: Date | string | null;
    invoiceId?: string | null;
    invoiceNo?: string | null;
    invoiceStatus?: string | null;
    invoiceSentAt?: Date | string | null;
    method?: string | null;
    paidProvider?: string | null;
    receiptUrl?: string | null;
    reminderCount?: number;
    createdAt: Date | string;
};

type Student = {
    id: string;
    name: string;
};

type Summary = {
    totalCount: number;
    totalAmount: number;
    paidAmount: number;
    unpaidAmount: number;
    paidCount: number;
    unpaidCount: number;
};

type FinancePayload = {
    payments: Payment[];
    summary: Summary;
};

type PaymentReconcilePreview = {
    batch: {
        id: string;
        createdAt: string;
        completedAt: string | null;
        spreadsheetTitle: string | null;
    } | null;
    year: number;
    month: number;
    summary: {
        create: number;
        update: number;
        unchanged: number;
        review: number;
        createAmount: number;
        updateAmount: number;
        reviewAmount: number;
    };
    samples: {
        studentId: string;
        studentName: string;
        rowCount: number;
        paymentMethods: string[] | null;
        targetStatus: string | null;
        targetAmount: number | null;
        targetMethod: string | null;
        existingStatus: string | null;
        existingAmount: number | null;
        existingMethod: string | null;
        reviewReason: string | null;
        action: "CREATE" | "UPDATE" | "UNCHANGED" | "REVIEW";
    }[];
};

type MonthlyInvoicePreview = {
    year: number;
    month: number;
    activeTemplateCount: number;
    targetStudentCount: number;
    createCount: number;
    skipCount: number;
    createAmount: number;
    skipAmount: number;
    samples: {
        studentId: string;
        studentName: string;
        templateName: string;
        type: string;
        amount: number;
        dueDay: number;
        action: "CREATE" | "SKIP";
    }[];
};

const EMPTY_SUMMARY: Summary = {
    totalCount: 0,
    totalAmount: 0,
    paidAmount: 0,
    unpaidAmount: 0,
    paidCount: 0,
    unpaidCount: 0,
};

const MONTHLY_INVOICE_ACTION_LABELS: Record<string, string> = {
    CREATE: "생성 예정",
    SKIP: "기존 청구 유지",
};

// 상태 라벨 + 색상 매핑
const STATUS_LABELS: Record<string, { label: string; color: string }> = {
    PENDING: { label: "미납", color: "bg-yellow-100 text-yellow-700" },
    PAID: { label: "납부완료", color: "bg-green-100 text-green-700" },
    OVERDUE: { label: "연체", color: "bg-red-100 text-red-700" },
    REFUNDED: { label: "환불", color: "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300" },
};

// 청구 유형 라벨
const TYPE_LABELS: Record<string, string> = {
    MONTHLY: "수강료",
    SHUTTLE: "셔틀",
    UNIFORM: "유니폼",
    OTHER: "기타",
};

const SHEET_RECONCILE_ACTION_LABELS: Record<string, string> = {
    CREATE: "생성",
    UPDATE: "수정",
    REVIEW: "확인 필요",
    UNCHANGED: "동일",
};

function toDateStr(d: Date | string | null): string {
    if (!d) return "-";
    const date = typeof d === "string" ? new Date(d) : d;
    return date.toISOString().split("T")[0];
}

function formatAmount(n: number): string {
    return n.toLocaleString("ko-KR") + "원";
}

function getErrorMessage(error: unknown, fallback: string) {
    return error instanceof Error ? error.message : fallback;
}

function FinanceLoadingFallback({ year, month }: { year: number; month: number }) {
    return (
        <div className="max-w-5xl mx-auto">
            <div className="flex flex-wrap justify-between items-start gap-3 mb-6">
                <div>
                    <div className="h-8 w-32 rounded bg-gray-200 dark:bg-gray-700 animate-pulse" />
                    <div className="h-4 w-64 rounded bg-gray-100 dark:bg-gray-800 animate-pulse mt-2" />
                </div>
                <div className="flex gap-2">
                    <div className="h-10 w-28 rounded-lg bg-gray-100 dark:bg-gray-800 animate-pulse" />
                    <div className="h-10 w-28 rounded-lg bg-gray-100 dark:bg-gray-800 animate-pulse" />
                    <div className="h-10 w-32 rounded-lg bg-gray-200 dark:bg-gray-700 animate-pulse" />
                </div>
            </div>
            <div className="flex items-center justify-center gap-4 mb-6">
                <div className="h-10 w-10 rounded-lg bg-gray-100 dark:bg-gray-800 animate-pulse" />
                <div className="h-7 w-28 rounded bg-gray-200 dark:bg-gray-700 animate-pulse" aria-label={`${year}년 ${month}월 수납 로딩 중`} />
                <div className="h-10 w-10 rounded-lg bg-gray-100 dark:bg-gray-800 animate-pulse" />
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
                {Array.from({ length: 4 }).map((_, index) => (
                    <div
                        key={index}
                        className="h-28 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 animate-pulse"
                    />
                ))}
            </div>
            <div className="overflow-hidden bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
                <div className="h-12 bg-gray-50 dark:bg-gray-900 border-b border-gray-100 dark:border-gray-700 animate-pulse" />
                <div className="divide-y divide-gray-100 dark:divide-gray-700">
                    {Array.from({ length: 6 }).map((_, index) => (
                        <div key={index} className="grid grid-cols-5 gap-4 px-4 py-4">
                            <div className="h-4 rounded bg-gray-100 dark:bg-gray-700 animate-pulse" />
                            <div className="h-4 rounded bg-gray-100 dark:bg-gray-700 animate-pulse" />
                            <div className="h-4 rounded bg-gray-100 dark:bg-gray-700 animate-pulse" />
                            <div className="h-4 rounded bg-gray-100 dark:bg-gray-700 animate-pulse" />
                            <div className="h-4 rounded bg-gray-100 dark:bg-gray-700 animate-pulse" />
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}

function FinanceErrorState({ onRetry }: { onRetry: () => void }) {
    return (
        <div className="mx-auto max-w-5xl rounded-2xl border border-red-100 bg-white p-8 text-center shadow-sm dark:border-red-900/40 dark:bg-gray-800">
            <span className="material-symbols-outlined mb-3 text-4xl text-red-500">error</span>
            <p className="font-bold text-gray-900 dark:text-white">수납 데이터를 불러오지 못했습니다.</p>
            <button
                type="button"
                onClick={onRetry}
                className="mt-4 rounded-xl bg-brand-orange-500 px-4 py-2 text-sm font-bold text-white transition hover:bg-orange-600 dark:bg-brand-neon-lime dark:text-brand-navy-900"
            >
                다시 시도
            </button>
        </div>
    );
}

export default function FinanceClient({
    initialPayments,
    initialYear,
    initialMonth,
    initialSummary,
}: {
    initialPayments?: Payment[];
    initialYear?: number;
    initialMonth?: number;
    initialSummary?: Summary;
}) {
    const now = new Date();
    const fallbackYear = now.getFullYear();
    const fallbackMonth = now.getMonth() + 1;
    const hasInitialData = Boolean(initialPayments && initialSummary);
    const [payments, setPayments] = useState(initialPayments ?? []);
    const [year, setYear] = useState(initialYear ?? fallbackYear);
    const [month, setMonth] = useState(initialMonth ?? fallbackMonth);
    const [loading, setLoading] = useState(!hasInitialData);
    const [loadError, setLoadError] = useState<string | null>(null);
    const [showForm, setShowForm] = useState(false);
    const [busy, setBusy] = useState(false);
    const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);
    const [summary, setSummary] = useState(initialSummary ?? EMPTY_SUMMARY);
    const [students, setStudents] = useState<Student[]>([]);
    const [studentsLoaded, setStudentsLoaded] = useState(false);
    const [studentsLoading, setStudentsLoading] = useState(false);
    const [studentsError, setStudentsError] = useState<string | null>(null);
    const [sheetPreview, setSheetPreview] = useState<PaymentReconcilePreview | null>(null);
    const [sheetPreviewLoading, setSheetPreviewLoading] = useState(false);
    const [sheetApplying, setSheetApplying] = useState(false);
    const [sheetError, setSheetError] = useState<string | null>(null);
    const [invoicePreview, setInvoicePreview] = useState<MonthlyInvoicePreview | null>(null);
    const [invoicePreviewLoading, setInvoicePreviewLoading] = useState(false);
    const [invoiceGenerating, setInvoiceGenerating] = useState(false);
    const [invoiceError, setInvoiceError] = useState<string | null>(null);

    const loadStudents = useCallback(async () => {
        if (studentsLoaded || studentsLoading) return;

        setStudentsLoading(true);
        setStudentsError(null);

        try {
            const response = await fetch("/api/admin/student-options");

            if (!response.ok) {
                throw new Error("Failed to load student options.");
            }

            const data = (await response.json()) as { students?: Student[] };
            setStudents(data.students ?? []);
            setStudentsLoaded(true);
        } catch (error) {
            console.error("Failed to load student options:", error);
            setStudentsError("학생 목록을 불러오지 못했습니다.");
        } finally {
            setStudentsLoading(false);
        }
    }, [studentsLoaded, studentsLoading]);

    // 일괄 체크박스 상태
    const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());

    // 수동 생성 폼 상태
    const [studentId, setStudentId] = useState("");
    const [amount, setAmount] = useState(0);
    const [dueDate, setDueDate] = useState("");
    const [status, setStatus] = useState("PENDING");
    const [paymentType, setPaymentType] = useState("MONTHLY");
    const [description, setDescription] = useState("");

    const hasAnyData = payments.length > 0 || summary.totalCount > 0;

    // 월 이동 시 데이터 재조회
    const loadMonth = useCallback(async (y: number, m: number) => {
        setYear(y);
        setMonth(m);
        setLoading(true);
        setLoadError(null);
        setSheetPreview(null);
        setSheetError(null);
        setInvoicePreview(null);
        setInvoiceError(null);
        setSelectedIds(new Set()); // 선택 초기화
        try {
            const res = await fetch(`/api/admin/finance?year=${y}&month=${m}`);
            if (!res.ok) {
                throw new Error("Failed to load finance data.");
            }
            const data = (await res.json()) as FinancePayload;
            setPayments(data.payments);
            setSummary(data.summary);
        } catch (err) {
            // 조회 실패 시 사용자에게 피드백 제공
            console.error("수납 데이터 조회 실패:", err);
            setLoadError("failed");
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        if (hasInitialData) return;
        void loadMonth(initialYear ?? fallbackYear, initialMonth ?? fallbackMonth);
    }, [fallbackMonth, fallbackYear, hasInitialData, initialMonth, initialYear, loadMonth]);

    function prevMonth() {
        const m = month === 1 ? 12 : month - 1;
        const y = month === 1 ? year - 1 : year;
        loadMonth(y, m);
    }

    function nextMonth() {
        const m = month === 12 ? 1 : month + 1;
        const y = month === 12 ? year + 1 : year;
        loadMonth(y, m);
    }

    // 수납 기록 수동 생성
    async function handleCreate(e: React.FormEvent) {
        e.preventDefault();
        if (!studentId || !amount || !dueDate) return;
        setBusy(true);
        try {
            // type과 description도 함께 전달 (수동 생성 시 유형/설명 저장)
            await createPayment({ studentId, amount, dueDate, status, type: paymentType, description: description || undefined });
            setShowForm(false);
            setStudentId("");
            setAmount(0);
            setDueDate("");
            setStatus("PENDING");
            setPaymentType("MONTHLY");
            setDescription("");
            await loadMonth(year, month);
        } catch (err: unknown) {
            alert(getErrorMessage(err, "생성 실패"));
        } finally {
            setBusy(false);
        }
    }

    // 개별 상태 변경
    async function handleStatusChange(id: string, newStatus: string) {
        setBusy(true);
        try {
            await updatePaymentStatus(id, newStatus);
            await loadMonth(year, month);
        } catch (err: unknown) {
            alert(getErrorMessage(err, "상태 변경 실패"));
        } finally {
            setBusy(false);
        }
    }

    // 개별 삭제
    async function handleDelete(id: string) {
        setBusy(true);
        try {
            await deletePayment(id);
            setDeleteConfirm(null);
            await loadMonth(year, month);
        } catch (err: unknown) {
            alert(getErrorMessage(err, "삭제 실패"));
        } finally {
            setBusy(false);
        }
    }

    // 이달 청구서 생성 대상 미리보기
    async function handlePreviewInvoices() {
        setInvoicePreviewLoading(true);
        setInvoiceError(null);

        try {
            const preview = await previewMonthlyInvoices(year, month);
            setInvoicePreview(preview);
        } catch (err: unknown) {
            setInvoiceError(getErrorMessage(err, "청구 대상 확인 실패"));
            setInvoicePreview(null);
        } finally {
            setInvoicePreviewLoading(false);
        }
    }

    // 이달 청구서 생성
    async function handleGenerateInvoices() {
        if (!invoicePreview) {
            await handlePreviewInvoices();
            return;
        }

        if (invoicePreview.createCount === 0) {
            alert("새로 생성할 청구서가 없습니다.");
            return;
        }

        const confirmMessage =
            `${year}년 ${month}월 청구서를 생성할까요?\n` +
            `생성 예정 ${invoicePreview.createCount}건, 총 ${formatAmount(invoicePreview.createAmount)}입니다.\n` +
            `기존 청구 ${invoicePreview.skipCount}건은 그대로 둡니다.`;

        if (!confirm(confirmMessage)) return;

        setInvoiceGenerating(true);
        setInvoiceError(null);

        try {
            const result = await generateMonthlyInvoices(year, month);
            alert(result.message);
            await loadMonth(year, month);
        } catch (err: unknown) {
            setInvoiceError(getErrorMessage(err, "청구서 생성 실패"));
        } finally {
            setInvoiceGenerating(false);
        }
    }

    // 미납 알림 일괄 발송
    async function handleSendReminders() {
        if (!confirm("미납 건에 대해 학부모 알림을 발송하시겠습니까?")) return;
        setBusy(true);
        try {
            const result = await sendUnpaidReminders();
            alert(result.message);
            await loadMonth(year, month);
        } catch (err: unknown) {
            alert(getErrorMessage(err, "알림 발송 실패"));
        } finally {
            setBusy(false);
        }
    }

    async function handleRefreshPaymentLedger() {
        setBusy(true);
        try {
            const result = await refreshPaymentLedger(year, month);
            alert(result.message);
            await loadMonth(year, month);
        } catch (err: unknown) {
            alert(getErrorMessage(err, "청구서 정리 실패"));
        } finally {
            setBusy(false);
        }
    }

    async function loadSheetPreview() {
        setSheetPreviewLoading(true);
        setSheetError(null);

        try {
            const response = await fetch(`/api/admin/finance/sheet-reconcile?year=${year}&month=${month}`, {
                cache: "no-store",
            });
            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "시트 기준 점검에 실패했습니다.");
            }

            setSheetPreview(data as PaymentReconcilePreview);
        } catch (err: unknown) {
            setSheetError(getErrorMessage(err, "시트 기준 점검에 실패했습니다."));
            setSheetPreview(null);
        } finally {
            setSheetPreviewLoading(false);
        }
    }

    async function applySheetPreview() {
        if (!sheetPreview) return;

        const createCount = sheetPreview.summary.create;
        const updateCount = sheetPreview.summary.update;
        const reviewCount = sheetPreview.summary.review;
        const confirmMessage =
            `${year}년 ${month}월 시트 원장을 기준으로 수납 기록을 반영할까요?\n` +
            `생성 ${createCount}건, 수정 ${updateCount}건이 적용됩니다.\n` +
            `확인 필요 ${reviewCount}건은 자동 변경하지 않습니다.`;

        if (!confirm(confirmMessage)) return;

        setSheetApplying(true);
        setSheetError(null);

        try {
            const response = await fetch(`/api/admin/finance/sheet-reconcile?year=${year}&month=${month}`, {
                method: "POST",
                cache: "no-store",
            });
            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "시트 기준 적용에 실패했습니다.");
            }

            await loadMonth(year, month);
            setSheetPreview((data.after ?? null) as PaymentReconcilePreview | null);
        } catch (err: unknown) {
            setSheetError(getErrorMessage(err, "시트 기준 적용에 실패했습니다."));
        } finally {
            setSheetApplying(false);
        }
    }

    // 일괄 수납 처리
    async function handleBulkPaid() {
        if (selectedIds.size === 0) { alert("선택된 항목이 없습니다."); return; }
        if (!confirm(`선택한 ${selectedIds.size}건을 납부완료 처리하시겠습니까?`)) return;
        setBusy(true);
        try {
            await bulkUpdatePaymentStatus(Array.from(selectedIds), "PAID");
            setSelectedIds(new Set());
            await loadMonth(year, month);
        } catch (err: unknown) {
            alert(getErrorMessage(err, "일괄 처리 실패"));
        } finally {
            setBusy(false);
        }
    }

    // 체크박스: 전체 선택/해제
    function toggleSelectAll() {
        if (selectedIds.size === payments.length) {
            setSelectedIds(new Set());
        } else {
            setSelectedIds(new Set(payments.map((p) => p.id)));
        }
    }

    // 체크박스: 개별 토글
    function toggleSelect(id: string) {
        const next = new Set(selectedIds);
        if (next.has(id)) next.delete(id);
        else next.add(id);
        setSelectedIds(next);
    }

    // 수납률 계산
    const payRate = summary.totalAmount > 0
        ? Math.round((summary.paidAmount / summary.totalAmount) * 100)
        : 0;
    const sheetApplyCount = sheetPreview
        ? sheetPreview.summary.create + sheetPreview.summary.update
        : 0;
    const invoiceCreateCount = invoicePreview?.createCount ?? 0;

    if (loading && !hasAnyData) {
        return <FinanceLoadingFallback year={year} month={month} />;
    }

    if (loadError && !hasAnyData) {
        return <FinanceErrorState onRetry={() => void loadMonth(year, month)} />;
    }

    return (
        <div className="max-w-5xl mx-auto">
            {/* 헤더 + 액션 버튼 */}
            <div className="flex flex-wrap justify-between items-start gap-3 mb-6">
                <div>
                    <h1 className="text-2xl font-extrabold text-gray-900 dark:text-white">수납/결제 관리</h1>
                    <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">원생별 수납 현황을 관리합니다.</p>
                </div>
                <div className="flex flex-wrap gap-2">
                    <button
                        onClick={loadSheetPreview}
                        disabled={busy || sheetPreviewLoading || sheetApplying}
                        className="bg-gray-900 text-white px-4 py-2 rounded-lg font-bold hover:bg-gray-800 transition disabled:opacity-50 text-sm dark:bg-brand-neon-lime dark:text-brand-navy-900"
                    >
                        <span className="material-symbols-outlined text-sm align-middle mr-1">fact_check</span>
                        {sheetPreviewLoading ? "점검 중..." : "시트 기준 점검"}
                    </button>
                    {/* 이달 청구서 생성 대상 확인 버튼 */}
                    <button
                        onClick={handlePreviewInvoices}
                        disabled={busy || invoicePreviewLoading || invoiceGenerating}
                        className="bg-blue-600 text-white px-4 py-2 rounded-lg font-bold hover:bg-blue-700 transition disabled:opacity-50 text-sm dark:bg-brand-neon-lime dark:text-brand-navy-900"
                    >
                        <span className="material-symbols-outlined text-sm align-middle mr-1">receipt_long</span>
                        {invoicePreviewLoading ? "확인 중..." : "청구 대상 확인"}
                    </button>
                    {/* 미납 알림 발송 버튼 */}
                    <button
                        onClick={handleRefreshPaymentLedger}
                        disabled={busy}
                        className="bg-emerald-600 text-white px-4 py-2 rounded-lg font-bold hover:bg-emerald-700 transition disabled:opacity-50 text-sm dark:bg-brand-neon-lime dark:text-brand-navy-900"
                    >
                        <span className="material-symbols-outlined text-sm align-middle mr-1">sync</span>
                        청구서 정리
                    </button>
                    <button
                        onClick={handleSendReminders}
                        disabled={busy}
                        className="bg-yellow-500 text-white px-4 py-2 rounded-lg font-bold hover:bg-yellow-600 transition disabled:opacity-50 text-sm"
                    >
                        <span className="material-symbols-outlined text-sm align-middle mr-1">notifications_active</span>
                        미납 알림 발송
                    </button>
                    {/* 수동 추가 버튼 */}
                    <button
                        onClick={() => {
                            const nextShowForm = !showForm;
                            setShowForm(nextShowForm);
                            if (nextShowForm) {
                                void loadStudents();
                            }
                        }}
                        className="bg-brand-orange-500 dark:bg-brand-neon-lime dark:text-brand-navy-900 text-white px-4 py-2 rounded-lg font-bold hover:bg-orange-600 transition text-sm"
                    >
                        + 수납 기록 추가
                    </button>
                </div>
            </div>

            {/* 월 네비게이션 */}
            <div className="flex items-center gap-4 mb-6">
                <button onClick={prevMonth} className="p-2 hover:bg-gray-100 dark:bg-gray-800 rounded-lg text-gray-600 dark:text-gray-300 font-bold">&larr;</button>
                <span className="text-lg font-bold text-gray-900 dark:text-white">{year}년 {month}월</span>
                <button onClick={nextMonth} className="p-2 hover:bg-gray-100 dark:bg-gray-800 rounded-lg text-gray-600 dark:text-gray-300 font-bold">&rarr;</button>
            </div>

            {(invoiceError || invoicePreview) && (
                <div className="mb-6 rounded-xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-800">
                    <div className="flex flex-wrap items-start justify-between gap-3">
                        <div>
                            <h2 className="text-base font-extrabold text-gray-900 dark:text-white">월별 청구 대상 확인</h2>
                            <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                                활성 청구 템플릿과 현재 수강 중인 학생을 기준으로 계산합니다. 기존 청구서는 중복 생성하지 않습니다.
                            </p>
                        </div>

                        {invoicePreview && (
                            <button
                                type="button"
                                onClick={handleGenerateInvoices}
                                disabled={invoiceGenerating || invoiceCreateCount === 0}
                                className="rounded-lg bg-brand-orange-500 px-4 py-2 text-sm font-bold text-white transition hover:bg-orange-600 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-brand-neon-lime dark:text-brand-navy-900"
                            >
                                {invoiceGenerating ? "생성 중..." : invoiceCreateCount === 0 ? "생성할 청구 없음" : "청구서 생성"}
                            </button>
                        )}
                    </div>

                    {invoiceError && (
                        <p className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-sm font-semibold text-red-700 dark:bg-red-950/30 dark:text-red-200">
                            {invoiceError}
                        </p>
                    )}

                    {invoicePreview && (
                        <>
                            <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
                                <div className="rounded-lg bg-gray-50 p-3 dark:bg-gray-900">
                                    <p className="text-xs font-bold text-gray-600 dark:text-gray-300">활성 템플릿</p>
                                    <p className="mt-1 text-xl font-extrabold text-gray-900 dark:text-white">{invoicePreview.activeTemplateCount}개</p>
                                    <p className="text-xs text-gray-500 dark:text-gray-400">청구 기준</p>
                                </div>
                                <div className="rounded-lg bg-blue-50 p-3 dark:bg-blue-950/30">
                                    <p className="text-xs font-bold text-blue-700 dark:text-blue-200">대상 학생</p>
                                    <p className="mt-1 text-xl font-extrabold text-blue-800 dark:text-blue-100">{invoicePreview.targetStudentCount}명</p>
                                    <p className="text-xs text-blue-600 dark:text-blue-300">현재 수강 중</p>
                                </div>
                                <div className="rounded-lg bg-green-50 p-3 dark:bg-green-950/30">
                                    <p className="text-xs font-bold text-green-700 dark:text-green-200">생성 예정</p>
                                    <p className="mt-1 text-xl font-extrabold text-green-800 dark:text-green-100">{invoicePreview.createCount}건</p>
                                    <p className="text-xs text-green-600 dark:text-green-300">{formatAmount(invoicePreview.createAmount)}</p>
                                </div>
                                <div className="rounded-lg bg-amber-50 p-3 dark:bg-amber-950/30">
                                    <p className="text-xs font-bold text-amber-700 dark:text-amber-200">기존 유지</p>
                                    <p className="mt-1 text-xl font-extrabold text-amber-800 dark:text-amber-100">{invoicePreview.skipCount}건</p>
                                    <p className="text-xs text-amber-600 dark:text-amber-300">중복 방지</p>
                                </div>
                            </div>

                            {invoicePreview.activeTemplateCount === 0 && (
                                <p className="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-sm font-semibold text-amber-700 dark:bg-amber-950/30 dark:text-amber-200">
                                    활성 청구 템플릿이 없습니다. 먼저 청구 템플릿을 등록해야 월별 청구서를 만들 수 있습니다.
                                </p>
                            )}

                            {invoicePreview.samples.length > 0 && (
                                <div className="mt-3 overflow-hidden rounded-lg border border-gray-100 dark:border-gray-700">
                                    {invoicePreview.samples.map((sample) => (
                                        <div key={`${sample.action}-${sample.studentId}-${sample.templateName}-${sample.type}`} className="flex flex-wrap items-center justify-between gap-2 border-b border-gray-100 px-3 py-2 text-sm last:border-b-0 dark:border-gray-700">
                                            <div>
                                                <span className="font-bold text-gray-900 dark:text-white">{sample.studentName}</span>
                                                <span className="ml-2 text-xs text-gray-500 dark:text-gray-400">
                                                    {sample.templateName} · {TYPE_LABELS[sample.type] ?? sample.type} · 매월 {sample.dueDay}일
                                                </span>
                                            </div>
                                            <div className="text-right">
                                                <span className={`rounded-full px-2 py-1 text-xs font-bold ${sample.action === "CREATE"
                                                    ? "bg-green-100 text-green-700 dark:bg-green-950/40 dark:text-green-200"
                                                    : "bg-gray-100 text-gray-700 dark:bg-gray-900 dark:text-gray-200"
                                                    }`}>
                                                    {MONTHLY_INVOICE_ACTION_LABELS[sample.action] ?? sample.action}
                                                </span>
                                                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">{formatAmount(sample.amount)}</p>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </>
                    )}
                </div>
            )}

            {(sheetError || sheetPreview) && (
                <div className="mb-6 rounded-xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-800">
                    <div className="flex flex-wrap items-start justify-between gap-3">
                        <div>
                            <h2 className="text-base font-extrabold text-gray-900 dark:text-white">시트 원장 기준 수납 점검</h2>
                            {sheetPreview?.batch ? (
                                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                                    마지막 가져오기: {toDateStr(sheetPreview.batch.completedAt ?? sheetPreview.batch.createdAt)}
                                    {sheetPreview.batch.spreadsheetTitle ? ` · ${sheetPreview.batch.spreadsheetTitle}` : ""}
                                </p>
                            ) : (
                                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">완료된 원장 가져오기 기록을 기준으로 비교합니다.</p>
                            )}
                        </div>

                        {sheetPreview && (
                            <button
                                type="button"
                                onClick={applySheetPreview}
                                disabled={sheetApplying || sheetApplyCount === 0}
                                className="rounded-lg bg-brand-orange-500 px-4 py-2 text-sm font-bold text-white transition hover:bg-orange-600 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-brand-neon-lime dark:text-brand-navy-900"
                            >
                                {sheetApplying ? "적용 중..." : sheetApplyCount === 0 ? "적용할 변경 없음" : "변경 적용"}
                            </button>
                        )}
                    </div>

                    {sheetError && (
                        <p className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-sm font-semibold text-red-700 dark:bg-red-950/30 dark:text-red-200">
                            {sheetError}
                        </p>
                    )}

                    {sheetPreview && (
                        <>
                            <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
                                <div className="rounded-lg bg-green-50 p-3 dark:bg-green-950/30">
                                    <p className="text-xs font-bold text-green-700 dark:text-green-200">생성</p>
                                    <p className="mt-1 text-xl font-extrabold text-green-800 dark:text-green-100">{sheetPreview.summary.create}건</p>
                                    <p className="text-xs text-green-600 dark:text-green-300">{formatAmount(sheetPreview.summary.createAmount)}</p>
                                </div>
                                <div className="rounded-lg bg-blue-50 p-3 dark:bg-blue-950/30">
                                    <p className="text-xs font-bold text-blue-700 dark:text-blue-200">수정</p>
                                    <p className="mt-1 text-xl font-extrabold text-blue-800 dark:text-blue-100">{sheetPreview.summary.update}건</p>
                                    <p className="text-xs text-blue-600 dark:text-blue-300">{formatAmount(sheetPreview.summary.updateAmount)}</p>
                                </div>
                                <div className="rounded-lg bg-amber-50 p-3 dark:bg-amber-950/30">
                                    <p className="text-xs font-bold text-amber-700 dark:text-amber-200">확인 필요</p>
                                    <p className="mt-1 text-xl font-extrabold text-amber-800 dark:text-amber-100">{sheetPreview.summary.review}건</p>
                                    <p className="text-xs text-amber-600 dark:text-amber-300">자동 변경 제외</p>
                                </div>
                                <div className="rounded-lg bg-gray-50 p-3 dark:bg-gray-900">
                                    <p className="text-xs font-bold text-gray-600 dark:text-gray-300">동일</p>
                                    <p className="mt-1 text-xl font-extrabold text-gray-900 dark:text-white">{sheetPreview.summary.unchanged}건</p>
                                    <p className="text-xs text-gray-500 dark:text-gray-400">변경 없음</p>
                                </div>
                            </div>

                            <p className="mt-3 text-xs text-gray-500 dark:text-gray-400">
                                휴원, 퇴원, 추가수강, 이월처럼 자동 판단이 위험한 건은 확인 필요로 남깁니다.
                            </p>

                            {sheetPreview.samples.length > 0 && (
                                <div className="mt-3 overflow-hidden rounded-lg border border-gray-100 dark:border-gray-700">
                                    {sheetPreview.samples.map((sample) => (
                                        <div key={`${sample.action}-${sample.studentId}`} className="flex flex-wrap items-center justify-between gap-2 border-b border-gray-100 px-3 py-2 text-sm last:border-b-0 dark:border-gray-700">
                                            <div>
                                                <span className="font-bold text-gray-900 dark:text-white">{sample.studentName}</span>
                                                <span className="ml-2 text-xs text-gray-500 dark:text-gray-400">
                                                    {sample.paymentMethods?.join(", ") || "-"} · {sample.rowCount}행
                                                </span>
                                                {sample.reviewReason && (
                                                    <p className="mt-0.5 text-xs text-amber-700 dark:text-amber-200">{sample.reviewReason}</p>
                                                )}
                                            </div>
                                            <div className="text-right">
                                                <span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-bold text-gray-700 dark:bg-gray-900 dark:text-gray-200">
                                                    {SHEET_RECONCILE_ACTION_LABELS[sample.action] ?? sample.action}
                                                </span>
                                                {sample.targetAmount != null && (
                                                    <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                                                        {sample.existingAmount != null ? `${formatAmount(sample.existingAmount)} → ` : ""}
                                                        {formatAmount(sample.targetAmount)}
                                                    </p>
                                                )}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </>
                    )}
                </div>
            )}

            {/* 요약 카드 (4개: 총 청구/수납/미납/수납률) */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
                <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-4">
                    <p className="text-xs text-gray-500 dark:text-gray-400 font-medium">총 청구</p>
                    <p className="text-xl font-extrabold text-gray-900 dark:text-white mt-1">{formatAmount(summary.totalAmount)}</p>
                    <p className="text-xs text-gray-400 mt-0.5">{summary.totalCount}건</p>
                </div>
                <div className="bg-white dark:bg-gray-800 border border-green-200 rounded-xl p-4">
                    <p className="text-xs text-green-600 font-medium">납부완료</p>
                    <p className="text-xl font-extrabold text-green-700 mt-1">{formatAmount(summary.paidAmount)}</p>
                    <p className="text-xs text-green-500 mt-0.5">{summary.paidCount}건</p>
                </div>
                <div className="bg-white dark:bg-gray-800 border border-yellow-200 rounded-xl p-4">
                    <p className="text-xs text-yellow-600 font-medium">미납/연체</p>
                    <p className="text-xl font-extrabold text-yellow-700 mt-1">{formatAmount(summary.unpaidAmount)}</p>
                    <p className="text-xs text-yellow-500 mt-0.5">{summary.unpaidCount}건</p>
                </div>
                <div className="bg-white dark:bg-gray-800 border border-blue-200 rounded-xl p-4">
                    <p className="text-xs text-blue-600 font-medium">수납률</p>
                    <p className="text-xl font-extrabold text-blue-700 mt-1">{payRate}%</p>
                    <div className="w-full bg-gray-200 rounded-full h-1.5 mt-2">
                        <div className="bg-blue-500 h-1.5 rounded-full transition-all" style={{ width: `${payRate}%` }} />
                    </div>
                </div>
            </div>

            {/* 일괄 처리 바 — 선택된 항목이 있을 때만 표시 */}
            {selectedIds.size > 0 && (
                <div className="bg-blue-50 border border-blue-200 rounded-xl p-3 mb-4 flex items-center justify-between">
                    <span className="text-sm font-medium text-blue-700">
                        {selectedIds.size}건 선택됨
                    </span>
                    <button
                        onClick={handleBulkPaid}
                        disabled={busy}
                        className="bg-green-600 text-white px-4 py-1.5 rounded-lg text-sm font-bold hover:bg-green-700 transition disabled:opacity-50"
                    >
                        선택 항목 납부 처리
                    </button>
                </div>
            )}

            {/* 수동 생성 폼 */}
            {showForm && (
                <form onSubmit={handleCreate} className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-6 mb-6 shadow-sm space-y-4">
                    <h3 className="font-bold text-lg text-gray-900 dark:text-white">새 수납 기록</h3>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">원생 *</label>
                            <select
                                value={studentId}
                                onChange={(e) => setStudentId(e.target.value)}
                                disabled={studentsLoading || Boolean(studentsError)}
                                required
                                className="w-full border border-gray-300 dark:border-gray-600 dark:text-white rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime bg-white dark:bg-gray-800"
                            >
                                <option value="">
                                    {studentsLoading ? "학생 목록 로딩 중..." : "선택하세요"}
                                </option>
                                {students.map((s) => (
                                    <option key={s.id} value={s.id}>{s.name}</option>
                                ))}
                            </select>
                            {studentsError && (
                                <div className="mt-2 flex items-center justify-between gap-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-200">
                                    <span>{studentsError}</span>
                                    <button
                                        type="button"
                                        onClick={() => void loadStudents()}
                                        className="shrink-0 rounded-md border border-red-200 px-2 py-1 text-xs font-medium text-red-700 hover:bg-red-100 dark:border-red-800 dark:text-red-200 dark:hover:bg-red-900/40"
                                    >
                                        다시 시도
                                    </button>
                                </div>
                            )}
                            {!studentsLoading && !studentsError && students.length === 0 && (
                                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                                    등록된 학생이 없습니다.
                                </p>
                            )}
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">금액 (원) *</label>
                            <input
                                type="number"
                                value={amount || ""}
                                onChange={(e) => setAmount(parseInt(e.target.value) || 0)}
                                required
                                placeholder="100000"
                                className="w-full border border-gray-300 dark:border-gray-600 dark:text-white dark:bg-gray-800 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">납부 기한 *</label>
                            <input
                                type="date"
                                min="2020-01-01" max="2030-12-31"
                                value={dueDate}
                                onChange={(e) => setDueDate(e.target.value)}
                                required
                                className="w-full border border-gray-300 dark:border-gray-600 dark:text-white dark:bg-gray-800 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">유형</label>
                            <select
                                value={paymentType}
                                onChange={(e) => setPaymentType(e.target.value)}
                                className="w-full border border-gray-300 dark:border-gray-600 dark:text-white rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime bg-white dark:bg-gray-800"
                            >
                                <option value="MONTHLY">월 수강료</option>
                                <option value="SHUTTLE">셔틀</option>
                                <option value="UNIFORM">유니폼</option>
                                <option value="OTHER">기타</option>
                            </select>
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">상태</label>
                            <select
                                value={status}
                                onChange={(e) => setStatus(e.target.value)}
                                className="w-full border border-gray-300 dark:border-gray-600 dark:text-white rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime bg-white dark:bg-gray-800"
                            >
                                <option value="PENDING">미납</option>
                                <option value="PAID">납부완료</option>
                                <option value="OVERDUE">연체</option>
                            </select>
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-200 mb-1">설명 (선택)</label>
                            <input
                                type="text"
                                value={description}
                                onChange={(e) => setDescription(e.target.value)}
                                placeholder="예: 4월 수강료"
                                className="w-full border border-gray-300 dark:border-gray-600 dark:text-white dark:bg-gray-800 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-brand-orange-500 dark:focus:ring-brand-neon-lime"
                            />
                        </div>
                    </div>
                    <div className="flex gap-2 justify-end">
                        <button type="button" onClick={() => setShowForm(false)} className="px-4 py-2 text-sm text-gray-600 dark:text-gray-300">취소</button>
                        <button type="submit" disabled={busy} className="bg-brand-orange-500 dark:bg-brand-neon-lime dark:text-brand-navy-900 text-white px-6 py-2 rounded-lg font-bold hover:bg-orange-600 transition disabled:opacity-50">
                            {busy ? "저장 중..." : "추가"}
                        </button>
                    </div>
                </form>
            )}

            {/* 수납 목록 테이블 */}
            {payments.length === 0 ? (
                <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-12 text-center text-gray-400">
                    {year}년 {month}월 수납 기록이 없습니다.
                </div>
            ) : (
                <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden shadow-sm">
                    <div className="overflow-x-auto">
                        <table className="min-w-full divide-y divide-gray-200">
                            <thead className="bg-gray-50 dark:bg-gray-900">
                                <tr>
                                    {/* 전체 선택 체크박스 */}
                                    <th className="px-3 py-3 text-center">
                                        <input
                                            type="checkbox"
                                            checked={selectedIds.size === payments.length && payments.length > 0}
                                            onChange={toggleSelectAll}
                                            className="rounded border-gray-300"
                                        />
                                    </th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">원생</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">유형</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">금액</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">납부기한</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">납부일</th>
                                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">상태</th>
                                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">관리</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100">
                                {payments.map((p) => {
                                    const statusInfo = STATUS_LABELS[p.status] || STATUS_LABELS.PENDING;
                                    return (
                                        <tr key={p.id} className={`hover:bg-gray-50 dark:bg-gray-900 transition-colors ${selectedIds.has(p.id) ? "bg-blue-50" : ""}`}>
                                            {/* 개별 체크박스 */}
                                            <td className="px-3 py-3.5 text-center">
                                                <input
                                                    type="checkbox"
                                                    checked={selectedIds.has(p.id)}
                                                    onChange={() => toggleSelect(p.id)}
                                                    className="rounded border-gray-300"
                                                />
                                            </td>
                                            <td className="px-4 py-3.5">
                                                <span className="font-medium text-gray-900 dark:text-white">{p.studentName}</span>
                                                {p.description && (
                                                    <p className="text-xs text-gray-400 mt-0.5">{p.description}</p>
                                                )}
                                                {p.invoiceNo && (
                                                    <p className="mt-1 text-[11px] font-bold text-brand-orange-500 dark:text-brand-neon-lime">
                                                        {p.invoiceNo}
                                                    </p>
                                                )}
                                                {p.autoGenerated && (
                                                    <span className="text-[10px] bg-blue-50 text-blue-500 px-1.5 py-0.5 rounded ml-1">자동</span>
                                                )}
                                            </td>
                                            <td className="px-4 py-3.5 text-sm text-gray-600 dark:text-gray-300">
                                                {TYPE_LABELS[p.type] || p.type}
                                                {(p.method || p.paidProvider) && (
                                                    <p className="mt-1 text-[11px] text-gray-400">
                                                        {[p.method, p.paidProvider].filter(Boolean).join(" · ")}
                                                    </p>
                                                )}
                                            </td>
                                            <td className="px-4 py-3.5 text-sm text-gray-700 dark:text-gray-200 font-mono">{formatAmount(p.amount)}</td>
                                            <td className="px-4 py-3.5 text-sm text-gray-600 dark:text-gray-300">{toDateStr(p.dueDate)}</td>
                                            <td className="px-4 py-3.5 text-sm text-gray-600 dark:text-gray-300">{toDateStr(p.paidDate)}</td>
                                            <td className="px-4 py-3.5">
                                                <span className={`text-xs font-bold px-2 py-1 rounded-full ${statusInfo.color}`}>
                                                    {statusInfo.label}
                                                </span>
                                                {p.notifiedAt && (
                                                    <span className="text-[10px] text-gray-400 block mt-0.5">
                                                        알림 {toDateStr(p.notifiedAt)}
                                                    </span>
                                                )}
                                                {Boolean(p.reminderCount) && (
                                                    <span className="text-[10px] text-gray-400 block mt-0.5">
                                                        알림 {p.reminderCount}회
                                                    </span>
                                                )}
                                            </td>
                                            <td className="px-4 py-3.5 text-right">
                                                <div className="flex items-center gap-2 justify-end">
                                                    {p.status !== "PAID" && (
                                                        <button
                                                            onClick={() => handleStatusChange(p.id, "PAID")}
                                                            disabled={busy}
                                                            className="text-xs text-green-600 hover:text-green-800 font-medium"
                                                        >
                                                            납부처리
                                                        </button>
                                                    )}
                                                    {p.status === "PENDING" && (
                                                        <button
                                                            onClick={() => handleStatusChange(p.id, "OVERDUE")}
                                                            disabled={busy}
                                                            className="text-xs text-yellow-600 hover:text-yellow-800 font-medium"
                                                        >
                                                            연체처리
                                                        </button>
                                                    )}
                                                    {p.status === "PAID" && (
                                                        <button
                                                            onClick={() => handleStatusChange(p.id, "REFUNDED")}
                                                            disabled={busy}
                                                            className="text-xs text-gray-500 hover:text-gray-700 dark:text-gray-200 font-medium"
                                                        >
                                                            환불
                                                        </button>
                                                    )}
                                                    {deleteConfirm === p.id ? (
                                                        <div className="flex gap-1">
                                                            <button onClick={() => handleDelete(p.id)} disabled={busy}
                                                                className="text-xs bg-red-500 text-white px-2 py-1 rounded font-bold disabled:opacity-50">확인</button>
                                                            <button onClick={() => setDeleteConfirm(null)}
                                                                className="text-xs text-gray-500 dark:text-gray-400 px-2 py-1">취소</button>
                                                        </div>
                                                    ) : (
                                                        <button onClick={() => setDeleteConfirm(p.id)}
                                                            className="text-xs text-red-500 hover:text-red-700 font-medium">삭제</button>
                                                    )}
                                                </div>
                                            </td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
}
