"use client";
import { useState } from "react";
import type { StaffBillingListItem } from "@/lib/staff-portal-queries";
const labels: Record<string, string> = { PENDING: "납부 전", OVERDUE: "기한 지남", PAID: "납부 완료", REFUNDED: "환불" };

export default function StaffBillingClient({ bills }: { bills: StaffBillingListItem[] }) {
  const [filter, setFilter] = useState<"OPEN" | "ALL">("OPEN");
  const visible = filter === "OPEN" ? bills.filter((bill) => bill.status === "PENDING" || bill.status === "OVERDUE") : bills;
  return <main className="mx-auto max-w-lg space-y-4 px-4 py-5"><header><p className="text-sm font-bold text-[var(--brand-accent)]">조회 전용</p><h1 className="mt-1 text-2xl font-black text-brand-navy-900 dark:text-white">청구 확인</h1><p className="mt-1 text-sm text-gray-500">현장 납부 처리는 관리자 확인 후 반영됩니다.</p></header>
    <div className="grid grid-cols-2 rounded-xl bg-gray-100 p-1 dark:bg-gray-800">{([['OPEN', '미납'], ['ALL', '전체']] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setFilter(value)} className={`min-h-10 rounded-lg text-sm font-bold ${filter === value ? "bg-white text-[var(--brand-accent)] shadow-sm dark:bg-gray-900" : "text-gray-500"}`}>{label}</button>)}</div>
    {visible.length === 0 ? <div className="rounded-2xl border border-dashed border-gray-300 bg-white p-8 text-center dark:border-gray-700 dark:bg-gray-900"><span className="material-symbols-outlined text-4xl text-gray-400">verified_user</span><p className="mt-2 font-bold text-gray-700 dark:text-gray-200">확인 가능한 청구가 없습니다.</p><p className="mt-1 text-sm leading-6 text-gray-500">담당 수업과 정확히 연결된 청구만 표시합니다. 현장 납부나 청구 상태는 관리자에게 확인해 주세요.</p></div> : visible.map((bill) => { const overdue = bill.status === "OVERDUE"; return <article key={bill.id} className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-900"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black dark:text-white">{bill.studentName}</h2><p className="mt-1 text-sm text-gray-500">{bill.title}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${overdue ? "bg-red-50 text-red-600 dark:bg-red-950" : "bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-300"}`}>{labels[bill.status] ?? bill.status}</span></div><p className="mt-4 text-xl font-black dark:text-white">{bill.amount.toLocaleString("ko-KR")}원</p><p className="mt-1 text-xs text-gray-500">납부 기한 {new Intl.DateTimeFormat("ko-KR").format(new Date(bill.dueDate))}{bill.invoiceNo ? ` · ${bill.invoiceNo}` : ""}</p>{(bill.status === "PENDING" || bill.status === "OVERDUE") && <div className="mt-4 rounded-xl bg-gray-50 p-3 text-sm text-gray-600 dark:bg-gray-800 dark:text-gray-300"><span className="material-symbols-outlined mr-1 align-middle text-lg">info</span>납부를 받았다면 관리자에게 확인을 요청해 주세요.</div>}</article>; })}
  </main>;
}
