"use client";
import { useState, useTransition } from "react";
import { requestStaffPaymentConfirmation } from "@/app/actions/staff-billing";
import type { StaffBillingListItem } from "@/lib/staff-portal-queries";

const labels: Record<string,string>={PENDING:"납부 전",OVERDUE:"기한 지남",PAID:"납부 완료",REFUNDED:"환불"};
export default function StaffBillingClient({bills}:{bills:StaffBillingListItem[]}){
 const [filter,setFilter]=useState<"OPEN"|"ALL">("OPEN"); const [target,setTarget]=useState<StaffBillingListItem|null>(null); const [method,setMethod]=useState("BANK_TRANSFER"); const [note,setNote]=useState(""); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
 const visible=filter==="OPEN"?bills.filter(b=>["PENDING","OVERDUE"].includes(b.status)):bills;
 function submit(){if(!target)return;startTransition(async()=>{const result=await requestStaffPaymentConfirmation({paymentId:target.id,method,receivedAt:new Date().toISOString(),note});setMessage(result.message);if(result.ok){setTarget(null);location.reload();}})}
 return <main className="mx-auto max-w-lg space-y-4 px-4 py-5"><header><p className="text-sm font-bold text-[var(--brand-accent)]">담당 수업 전용</p><h1 className="mt-1 text-2xl font-black">청구 확인</h1><p className="mt-1 text-sm text-gray-500">현금·계좌이체 수납은 관리자 승인 후 납부 완료됩니다.</p></header>
 <div className="grid grid-cols-2 rounded-xl bg-gray-100 p-1">{([["OPEN","미납"],["ALL","전체"]] as const).map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`min-h-10 rounded-lg font-bold ${filter===v?"bg-white text-[var(--brand-accent)] shadow-sm":"text-gray-500"}`}>{l}</button>)}</div>
 {message&&<p className="rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-700">{message}</p>}
 {visible.length===0?<div className="rounded-2xl border border-dashed p-8 text-center"><span className="material-symbols-outlined text-4xl text-gray-400">verified_user</span><p className="mt-2 font-bold">표시할 담당 수업 청구가 없습니다.</p></div>:visible.map(b=><article key={b.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-black">{b.studentName}</h2><p className="text-sm text-gray-500">{b.className} · {b.title}</p></div><span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-bold">{labels[b.status]??b.status}</span></div><p className="mt-4 text-xl font-black">{b.amount.toLocaleString("ko-KR")}원</p><p className="text-xs text-gray-500">납부 기한 {new Intl.DateTimeFormat("ko-KR").format(new Date(b.dueDate))}</p>{b.confirmationStatus==="PENDING"?<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-700">관리자 확인 대기 중</p>:["PENDING","OVERDUE"].includes(b.status)&&<button onClick={()=>{setTarget(b);setMessage("")}} className="mt-3 min-h-11 w-full rounded-xl bg-[var(--brand-accent)] font-black text-[var(--brand-accent-contrast)]">납부 확인 요청</button>}</article>)}
 {target&&<div className="fixed inset-0 z-50 flex items-end bg-black/50 p-4"><div className="w-full rounded-2xl bg-white p-5"><h2 className="text-xl font-black">납부 확인 요청</h2><p className="mt-1 text-sm text-gray-500">{target.studentName} · {target.amount.toLocaleString()}원</p><select value={method} onChange={e=>setMethod(e.target.value)} className="mt-4 min-h-12 w-full rounded-xl border px-3"><option value="BANK_TRANSFER">계좌이체</option><option value="CASH">현금</option></select><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} placeholder="수납 메모" className="mt-3 w-full rounded-xl border p-3"/><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setTarget(null)} className="min-h-12 rounded-xl border font-bold">취소</button><button disabled={pending} onClick={submit} className="min-h-12 rounded-xl bg-[var(--brand-accent)] font-black text-[var(--brand-accent-contrast)]">확인 요청</button></div></div></div>}
 </main>;
}
