/**
 * GET /api/cron/billing
 *
 * Vercel Cron이 매월 1일 KST 오전 9시(UTC 0시)에 호출합니다.
 * 활성 청구 템플릿 기준으로 해당 월의 청구서를 자동 생성합니다.
 *
 * vercel.json:
 *   "crons": [{ "path": "/api/cron/billing", "schedule": "0 0 1 * *" }]
 */

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export async function GET(req: NextRequest) {
    // CRON_SECRET 검증 — 개발환경 예외
    const cronSecret = process.env.CRON_SECRET;
    if (process.env.NODE_ENV !== "development") {
        if (!cronSecret || req.headers.get("authorization") !== `Bearer ${cronSecret}`) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }
    }

    try {
        // 현재 KST 기준 연/월 계산
        const now = new Date();
        const kstNow = new Date(now.getTime() + 9 * 60 * 60 * 1000);
        const year = kstNow.getFullYear();
        const month = kstNow.getMonth() + 1;

        // 1) BillingTemplate 테이블 존재 확인 (DDL)
        await prisma.$executeRawUnsafe(`
            CREATE TABLE IF NOT EXISTS "BillingTemplate" (
                id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
                name TEXT NOT NULL,
                amount INTEGER NOT NULL,
                type TEXT DEFAULT 'MONTHLY',
                description TEXT,
                "isActive" BOOLEAN DEFAULT true,
                "dueDay" INTEGER DEFAULT 10,
                "programId" TEXT,
                "createdAt" TIMESTAMPTZ DEFAULT NOW(),
                "updatedAt" TIMESTAMPTZ DEFAULT NOW()
            )
        `);

        // Payment 새 컬럼 존재 확인
        const paymentCols: [string, string][] = [
            ["type", "TEXT DEFAULT 'MONTHLY'"],
            ["description", "TEXT"],
            ["month", "INTEGER"],
            ["year", "INTEGER"],
            ["autoGenerated", "BOOLEAN DEFAULT false"],
            ["notifiedAt", "TIMESTAMPTZ"],
        ];
        for (const [col, colType] of paymentCols) {
            try {
                await prisma.$executeRawUnsafe(
                    `ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "${col}" ${colType}`
                );
            } catch {}
        }

        // 2) 활성 템플릿 조회
        const templates = await prisma.$queryRawUnsafe<any[]>(
            `SELECT id, name, amount, type, description, "dueDay"
             FROM "BillingTemplate" WHERE "isActive" = true`
        );

        if (templates.length === 0) {
            return NextResponse.json({
                success: true,
                message: "활성 청구 템플릿 없음",
                created: 0,
                skipped: 0,
            });
        }

        // 3) ACTIVE 수강생 목록 (중복 제거)
        const students = await prisma.$queryRawUnsafe<any[]>(
            `SELECT DISTINCT s.id
             FROM "Student" s
             JOIN "Enrollment" e ON s.id = e."studentId"
             WHERE e.status = 'ACTIVE'`
        );

        let created = 0;
        let skipped = 0;

        // 4) 학생 x 템플릿 조합별 청구서 생성 (중복 방지)
        for (const tpl of templates) {
            const dueDay = Math.min(Number(tpl.dueDay ?? tpl.dueday ?? 10), 28);
            const dueDateStr = `${year}-${String(month).padStart(2, "0")}-${String(dueDay).padStart(2, "0")}`;
            const tplType = tpl.type ?? "MONTHLY";
            const tplDesc = tpl.description || tpl.name;

            for (const stu of students) {
                // 중복 검사
                const existing = await prisma.$queryRawUnsafe<any[]>(
                    `SELECT id FROM "Payment"
                     WHERE "studentId" = $1 AND year = $2 AND month = $3 AND type = $4
                     LIMIT 1`,
                    stu.id, year, month, tplType,
                );
                if (existing.length > 0) {
                    skipped++;
                    continue;
                }

                await prisma.$executeRawUnsafe(
                    `INSERT INTO "Payment" (id, "studentId", amount, status, "dueDate", type, description, month, year, "autoGenerated", "createdAt", "updatedAt")
                     VALUES (gen_random_uuid()::text, $1, $2, 'PENDING', $3::timestamp, $4, $5, $6, $7, true, NOW(), NOW())`,
                    stu.id,
                    Number(tpl.amount),
                    dueDateStr,
                    tplType,
                    tplDesc,
                    month,
                    year,
                );
                created++;
            }
        }

        return NextResponse.json({
            success: true,
            year,
            month,
            templates: templates.length,
            students: students.length,
            created,
            skipped,
        });
    } catch (e) {
        console.error("[cron/billing] failed:", e);
        return NextResponse.json({ error: "서버 오류가 발생했습니다." }, { status: 500 });
    }
}
